//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

type Genre string

const (
	GenreFiction Genre = "fiction"
	GenreScience Genre = "science"
	GenreHistory Genre = "history"
)

func (e *Genre) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = Genre(s)
	case string:
		*e = Genre(s)
	default:
		return fmt.Errorf("unsupported scan type for Genre: %T", src)
	}
	return nil
}

type NullGenre struct {
	Genre Genre `json:"genre"`
	Valid bool  `json:"valid"` // Valid is true if Genre is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenre) Scan(value any) error {
	if value == nil {
		ns.Genre, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Genre.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenre) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Genre), nil
}

type Author struct {
	ID         int32           `json:"id"`
	Name       string          `json:"name"`
	Bio        *string         `json:"bio"`
	Email      *string         `json:"email"`
	Born       *time.Time      `json:"born"`
	Rating     *string         `json:"rating"`
	Tags       []string        `json:"tags"`
	Meta       json.RawMessage `json:"meta"`
	ExternalID *uuid.UUID      `json:"external_id"`
	Active     bool            `json:"active"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  *time.Time      `json:"updated_at"`
}

type Book struct {
	ID        int64           `json:"id"`
	AuthorID  int32           `json:"author_id"`
	Title     string          `json:"title"`
	Genre     Genre           `json:"genre"`
	Pages     *int32          `json:"pages"`
	Price     string          `json:"price"`
	Weight    *float64        `json:"weight"`
	Isbn      uuid.UUID       `json:"isbn"`
	Published *time.Time      `json:"published"`
	Scores    []int32         `json:"scores"`
	Extra     json.RawMessage `json:"extra"`
	CreatedAt time.Time       `json:"created_at"`
}

type Sample struct {
	ID     int32             `json:"id"`
	B      bool              `json:"b"`
	Nb     *bool             `json:"nb"`
	I1     int8              `json:"i1"`
	Ni1    *int8             `json:"ni1"`
	I2     int16             `json:"i2"`
	Ni2    *int16            `json:"ni2"`
	I4     int32             `json:"i4"`
	Ni4    *int32            `json:"ni4"`
	I8     int64             `json:"i8"`
	Ni8    *int64            `json:"ni8"`
	U1     uint8             `json:"u1"`
	Nu1    *uint8            `json:"nu1"`
	U2     uint16            `json:"u2"`
	Nu2    *uint16           `json:"nu2"`
	U4     uint32            `json:"u4"`
	Nu4    *uint32           `json:"nu4"`
	U8     uint64            `json:"u8"`
	Nu8    *uint64           `json:"nu8"`
	H      *big.Int          `json:"h"`
	Nh     *big.Int          `json:"nh"`
	Uh     *big.Int          `json:"uh"`
	Nuh    *big.Int          `json:"nuh"`
	F4     float32           `json:"f4"`
	Nf4    *float32          `json:"nf4"`
	F8     float64           `json:"f8"`
	Nf8    *float64          `json:"nf8"`
	D      string            `json:"d"`
	Nd     *string           `json:"nd"`
	S      string            `json:"s"`
	Ns     *string           `json:"ns"`
	T      string            `json:"t"`
	Nt     *string           `json:"nt"`
	Bl     []byte            `json:"bl"`
	Nbl    []byte            `json:"nbl"`
	Dt     time.Time         `json:"dt"`
	Ndt    *time.Time        `json:"ndt"`
	Tm     time.Time         `json:"tm"`
	Ntm    *time.Time        `json:"ntm"`
	Ts     time.Time         `json:"ts"`
	Nts    *time.Time        `json:"nts"`
	Tstz   time.Time         `json:"tstz"`
	Ntstz  *time.Time        `json:"ntstz"`
	Iv     duckdb.Interval   `json:"iv"`
	Niv    *duckdb.Interval  `json:"niv"`
	U      uuid.UUID         `json:"u"`
	Nu     *uuid.UUID        `json:"nu"`
	J      json.RawMessage   `json:"j"`
	Nj     json.RawMessage   `json:"nj"`
	G      Genre             `json:"g"`
	Ng     *Genre            `json:"ng"`
	E      string            `json:"e"`
	Ne     *string           `json:"ne"`
	Li     []int32           `json:"li"`
	Nli    []int32           `json:"nli"`
	Ls     []string          `json:"ls"`
	Nls    []string          `json:"nls"`
	Lu     []uuid.UUID       `json:"lu"`
	Nlu    []uuid.UUID       `json:"nlu"`
	Lj     []json.RawMessage `json:"lj"`
	Nlj    []json.RawMessage `json:"nlj"`
	Fixed  []int32           `json:"fixed"`
	Nfixed []int32           `json:"nfixed"`
	St     map[string]any    `json:"st"`
	Nst    *map[string]any   `json:"nst"`
	M      duckdb.Map        `json:"m"`
	Nm     *duckdb.Map       `json:"nm"`
}
