//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
	"encoding/json"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

const authorTags = `-- name: AuthorTags :many
SELECT a.id, t.tag FROM authors a, unnest(a.tags) AS t(tag);
`

type AuthorTagsRow struct {
	ID  int32   `json:"id"`
	Tag *string `json:"tag"`
}

func (q *Queries) AuthorTags(ctx context.Context) ([]AuthorTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, authorTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorTagsRow
	for rows.Next() {
		var i AuthorTagsRow
		if err := rows.Scan(&i.ID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorsTagged = `-- name: AuthorsTagged :many
SELECT id, name FROM authors WHERE list_contains(tags, $1);
`

type AuthorsTaggedRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) AuthorsTagged(ctx context.Context, tag string) ([]AuthorsTaggedRow, error) {
	rows, err := q.db.QueryContext(ctx, authorsTagged, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsTaggedRow
	for rows.Next() {
		var i AuthorsTaggedRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorsWithBookCount = `-- name: AuthorsWithBookCount :many
SELECT a.id, a.name, count(b.id) AS book_count, sum(b.price) AS total_price, max(b.published) AS latest
FROM authors a
LEFT JOIN books b ON b.author_id = a.id
GROUP BY a.id, a.name
ORDER BY book_count DESC;
`

type AuthorsWithBookCountRow struct {
	ID         int32      `json:"id"`
	Name       string     `json:"name"`
	BookCount  int64      `json:"book_count"`
	TotalPrice *string    `json:"total_price"`
	Latest     *time.Time `json:"latest"`
}

func (q *Queries) AuthorsWithBookCount(ctx context.Context) ([]AuthorsWithBookCountRow, error) {
	rows, err := q.db.QueryContext(ctx, authorsWithBookCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsWithBookCountRow
	for rows.Next() {
		var i AuthorsWithBookCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BookCount,
			duckdbDecimal(&i.TotalPrice),
			&i.Latest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookMeta = `-- name: BookMeta :one
SELECT extra->>'publisher' AS publisher, extra->'dims' AS dims, list_contains(scores, 5) AS has_five, len(scores) AS n_scores
FROM books WHERE id = $1;
`

type BookMetaRow struct {
	Publisher *string         `json:"publisher"`
	Dims      json.RawMessage `json:"dims"`
	HasFive   *bool           `json:"has_five"`
	NScores   *int64          `json:"n_scores"`
}

func (q *Queries) BookMeta(ctx context.Context, id int64) (BookMetaRow, error) {
	row := q.db.QueryRowContext(ctx, bookMeta, id)
	var i BookMetaRow
	err := row.Scan(
		&i.Publisher,
		duckdbJSON(&i.Dims),
		&i.HasFive,
		&i.NScores,
	)
	return i, err
}

const booksByIDs = `-- name: BooksByIDs :many
SELECT id, author_id, title, genre, pages, price, weight, isbn, published, scores, extra, created_at FROM books WHERE id = ANY($1);
`

func (q *Queries) BooksByIDs(ctx context.Context, ids []int64) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, booksByIDs, duckdbListParam(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Genre,
			&i.Pages,
			duckdbDecimal(&i.Price),
			&i.Weight,
			&i.Isbn,
			&i.Published,
			duckdbList(&i.Scores),
			duckdbJSON(&i.Extra),
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const booksWithAuthor = `-- name: BooksWithAuthor :many
SELECT books.id, books.author_id, books.title, books.genre, books.pages, books.price, books.weight, books.isbn, books.published, books.scores, books.extra, books.created_at, authors.id, authors.name, authors.bio, authors.email, authors.born, authors.rating, authors.tags, authors.meta, authors.external_id, authors.active, authors.created_at, authors.updated_at
FROM books
JOIN authors ON authors.id = books.author_id
WHERE books.genre = $1;
`

type BooksWithAuthorRow struct {
	Book   Book   `json:"book"`
	Author Author `json:"author"`
}

func (q *Queries) BooksWithAuthor(ctx context.Context, genre Genre) ([]BooksWithAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, booksWithAuthor, genre)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BooksWithAuthorRow
	for rows.Next() {
		var i BooksWithAuthorRow
		if err := rows.Scan(
			&i.Book.ID,
			&i.Book.AuthorID,
			&i.Book.Title,
			&i.Book.Genre,
			&i.Book.Pages,
			duckdbDecimal(&i.Book.Price),
			&i.Book.Weight,
			&i.Book.Isbn,
			&i.Book.Published,
			duckdbList(&i.Book.Scores),
			duckdbJSON(&i.Book.Extra),
			&i.Book.CreatedAt,
			&i.Author.ID,
			&i.Author.Name,
			&i.Author.Bio,
			&i.Author.Email,
			&i.Author.Born,
			duckdbDecimal(&i.Author.Rating),
			duckdbList(&i.Author.Tags),
			duckdbJSON(&i.Author.Meta),
			&i.Author.ExternalID,
			&i.Author.Active,
			&i.Author.CreatedAt,
			&i.Author.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const booksWithOptionalAuthor = `-- name: BooksWithOptionalAuthor :many
SELECT books.id, books.author_id, books.title, books.genre, books.pages, books.price, books.weight, books.isbn, books.published, books.scores, books.extra, books.created_at, authors.name AS author_name
FROM books
LEFT JOIN authors ON authors.id = books.author_id;
`

type BooksWithOptionalAuthorRow struct {
	Book       Book    `json:"book"`
	AuthorName *string `json:"author_name"`
}

func (q *Queries) BooksWithOptionalAuthor(ctx context.Context) ([]BooksWithOptionalAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, booksWithOptionalAuthor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BooksWithOptionalAuthorRow
	for rows.Next() {
		var i BooksWithOptionalAuthorRow
		if err := rows.Scan(
			&i.Book.ID,
			&i.Book.AuthorID,
			&i.Book.Title,
			&i.Book.Genre,
			&i.Book.Pages,
			duckdbDecimal(&i.Book.Price),
			&i.Book.Weight,
			&i.Book.Isbn,
			&i.Book.Published,
			duckdbList(&i.Book.Scores),
			duckdbJSON(&i.Book.Extra),
			&i.Book.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBooks = `-- name: CountBooks :one
SELECT count(*) FROM books WHERE author_id = $1;
`

func (q *Queries) CountBooks(ctx context.Context, authorID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio, email, born, rating, tags, meta, external_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, bio, email, born, rating, tags, meta, external_id, active, created_at, updated_at;
`

type CreateAuthorParams struct {
	Name       string          `json:"name"`
	Bio        *string         `json:"bio"`
	Email      *string         `json:"email"`
	Born       *time.Time      `json:"born"`
	Rating     *string         `json:"rating"`
	Tags       []string        `json:"tags"`
	Meta       json.RawMessage `json:"meta"`
	ExternalID *uuid.UUID      `json:"external_id"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor,
		arg.Name,
		arg.Bio,
		arg.Email,
		arg.Born,
		arg.Rating,
		duckdbListParam(arg.Tags),
		duckdbParam(arg.Meta),
		arg.ExternalID,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Email,
		&i.Born,
		duckdbDecimal(&i.Rating),
		duckdbList(&i.Tags),
		duckdbJSON(&i.Meta),
		&i.ExternalID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSample = `-- name: CreateSample :exec
INSERT INTO samples VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67);
`

type CreateSampleParams struct {
	ID     int32             `json:"id"`
	B      bool              `json:"b"`
	Nb     *bool             `json:"nb"`
	I1     int8              `json:"i1"`
	Ni1    *int8             `json:"ni1"`
	I2     int16             `json:"i2"`
	Ni2    *int16            `json:"ni2"`
	I4     int32             `json:"i4"`
	Ni4    *int32            `json:"ni4"`
	I8     int64             `json:"i8"`
	Ni8    *int64            `json:"ni8"`
	U1     uint8             `json:"u1"`
	Nu1    *uint8            `json:"nu1"`
	U2     uint16            `json:"u2"`
	Nu2    *uint16           `json:"nu2"`
	U4     uint32            `json:"u4"`
	Nu4    *uint32           `json:"nu4"`
	U8     uint64            `json:"u8"`
	Nu8    *uint64           `json:"nu8"`
	H      *big.Int          `json:"h"`
	Nh     *big.Int          `json:"nh"`
	Uh     *big.Int          `json:"uh"`
	Nuh    *big.Int          `json:"nuh"`
	F4     float32           `json:"f4"`
	Nf4    *float32          `json:"nf4"`
	F8     float64           `json:"f8"`
	Nf8    *float64          `json:"nf8"`
	D      string            `json:"d"`
	Nd     *string           `json:"nd"`
	S      string            `json:"s"`
	Ns     *string           `json:"ns"`
	T      string            `json:"t"`
	Nt     *string           `json:"nt"`
	Bl     []byte            `json:"bl"`
	Nbl    []byte            `json:"nbl"`
	Dt     time.Time         `json:"dt"`
	Ndt    *time.Time        `json:"ndt"`
	Tm     time.Time         `json:"tm"`
	Ntm    *time.Time        `json:"ntm"`
	Ts     time.Time         `json:"ts"`
	Nts    *time.Time        `json:"nts"`
	Tstz   time.Time         `json:"tstz"`
	Ntstz  *time.Time        `json:"ntstz"`
	Iv     duckdb.Interval   `json:"iv"`
	Niv    *duckdb.Interval  `json:"niv"`
	U      uuid.UUID         `json:"u"`
	Nu     *uuid.UUID        `json:"nu"`
	J      json.RawMessage   `json:"j"`
	Nj     json.RawMessage   `json:"nj"`
	G      Genre             `json:"g"`
	Ng     *Genre            `json:"ng"`
	E      string            `json:"e"`
	Ne     *string           `json:"ne"`
	Li     []int32           `json:"li"`
	Nli    []int32           `json:"nli"`
	Ls     []string          `json:"ls"`
	Nls    []string          `json:"nls"`
	Lu     []uuid.UUID       `json:"lu"`
	Nlu    []uuid.UUID       `json:"nlu"`
	Lj     []json.RawMessage `json:"lj"`
	Nlj    []json.RawMessage `json:"nlj"`
	Fixed  []int32           `json:"fixed"`
	Nfixed []int32           `json:"nfixed"`
	St     map[string]any    `json:"st"`
	Nst    *map[string]any   `json:"nst"`
	M      duckdb.Map        `json:"m"`
	Nm     *duckdb.Map       `json:"nm"`
}

func (q *Queries) CreateSample(ctx context.Context, arg CreateSampleParams) error {
	_, err := q.db.ExecContext(ctx, createSample,
		arg.ID,
		arg.B,
		arg.Nb,
		arg.I1,
		arg.Ni1,
		arg.I2,
		arg.Ni2,
		arg.I4,
		arg.Ni4,
		arg.I8,
		arg.Ni8,
		arg.U1,
		arg.Nu1,
		arg.U2,
		arg.Nu2,
		arg.U4,
		arg.Nu4,
		arg.U8,
		arg.Nu8,
		duckdbParam(arg.H),
		duckdbParam(arg.Nh),
		duckdbParam(arg.Uh),
		duckdbParam(arg.Nuh),
		arg.F4,
		arg.Nf4,
		arg.F8,
		arg.Nf8,
		arg.D,
		arg.Nd,
		arg.S,
		arg.Ns,
		arg.T,
		arg.Nt,
		duckdbParam(arg.Bl),
		duckdbParam(arg.Nbl),
		arg.Dt,
		arg.Ndt,
		arg.Tm,
		arg.Ntm,
		arg.Ts,
		arg.Nts,
		arg.Tstz,
		arg.Ntstz,
		arg.Iv,
		duckdbPtrParam(arg.Niv),
		arg.U,
		arg.Nu,
		duckdbParam(arg.J),
		duckdbParam(arg.Nj),
		arg.G,
		arg.Ng,
		arg.E,
		arg.Ne,
		duckdbListParam(arg.Li),
		duckdbListParam(arg.Nli),
		duckdbListParam(arg.Ls),
		duckdbListParam(arg.Nls),
		duckdbListParam(arg.Lu),
		duckdbListParam(arg.Nlu),
		duckdbListParam(arg.Lj),
		duckdbListParam(arg.Nlj),
		duckdbListParam(arg.Fixed),
		duckdbListParam(arg.Nfixed),
		arg.St,
		duckdbPtrParam(arg.Nst),
		arg.M,
		duckdbPtrParam(arg.Nm),
	)
	return err
}

const deleteAuthor = `-- name: DeleteAuthor :execresult
DELETE FROM authors WHERE id = $1;
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAuthor, id)
}

const deleteInactiveAuthors = `-- name: DeleteInactiveAuthors :exec
DELETE FROM authors WHERE NOT active AND created_at < current_date - INTERVAL 1 YEAR;
`

func (q *Queries) DeleteInactiveAuthors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteInactiveAuthors)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, bio, email, born, rating, tags, meta, external_id, active, created_at, updated_at FROM authors WHERE id = $1;
`

func (q *Queries) GetAuthor(ctx context.Context, id int32) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.Email,
		&i.Born,
		duckdbDecimal(&i.Rating),
		duckdbList(&i.Tags),
		duckdbJSON(&i.Meta),
		&i.ExternalID,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSample = `-- name: GetSample :one
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, nuh, f4, nf4, f8, nf8, d, nd, s, ns, t, nt, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, iv, niv, u, nu, j, nj, g, ng, e, ne, li, nli, ls, nls, lu, nlu, lj, nlj, fixed, nfixed, st, nst, m, nm FROM samples WHERE id = $1;
`

func (q *Queries) GetSample(ctx context.Context, id int32) (Sample, error) {
	row := q.db.QueryRowContext(ctx, getSample, id)
	var i Sample
	err := row.Scan(
		&i.ID,
		&i.B,
		&i.Nb,
		&i.I1,
		&i.Ni1,
		&i.I2,
		&i.Ni2,
		&i.I4,
		&i.Ni4,
		&i.I8,
		&i.Ni8,
		&i.U1,
		&i.Nu1,
		&i.U2,
		&i.Nu2,
		&i.U4,
		&i.Nu4,
		&i.U8,
		&i.Nu8,
		&i.H,
		&i.Nh,
		&i.Uh,
		&i.Nuh,
		&i.F4,
		&i.Nf4,
		&i.F8,
		&i.Nf8,
		duckdbDecimal(&i.D),
		duckdbDecimal(&i.Nd),
		&i.S,
		&i.Ns,
		&i.T,
		&i.Nt,
		&i.Bl,
		&i.Nbl,
		&i.Dt,
		&i.Ndt,
		&i.Tm,
		&i.Ntm,
		&i.Ts,
		&i.Nts,
		&i.Tstz,
		&i.Ntstz,
		&i.Iv,
		&i.Niv,
		&i.U,
		&i.Nu,
		duckdbJSON(&i.J),
		duckdbJSON(&i.Nj),
		&i.G,
		&i.Ng,
		&i.E,
		&i.Ne,
		duckdbList(&i.Li),
		duckdbList(&i.Nli),
		duckdbList(&i.Ls),
		duckdbList(&i.Nls),
		duckdbList(&i.Lu),
		duckdbList(&i.Nlu),
		duckdbList(&i.Lj),
		duckdbList(&i.Nlj),
		duckdbList(&i.Fixed),
		duckdbList(&i.Nfixed),
		&i.St,
		&i.Nst,
		&i.M,
		&i.Nm,
	)
	return i, err
}

const insertBooksBulk = `-- name: InsertBooksBulk :exec
INSERT INTO books (author_id, title, genre, price, isbn, extra)
SELECT unnest($1), unnest($2), unnest($3), unnest($4), unnest($5), unnest($6);
`

type InsertBooksBulkParams struct {
	AuthorID []int32           `json:"author_id"`
	Title    []string          `json:"title"`
	Genre    []Genre           `json:"genre"`
	Price    []string          `json:"price"`
	Isbn     []uuid.UUID       `json:"isbn"`
	Extra    []json.RawMessage `json:"extra"`
}

func (q *Queries) InsertBooksBulk(ctx context.Context, arg InsertBooksBulkParams) error {
	_, err := q.db.ExecContext(ctx, insertBooksBulk,
		duckdbListParam(arg.AuthorID),
		duckdbListParam(arg.Title),
		duckdbListParam(arg.Genre),
		duckdbListParam(arg.Price),
		duckdbListParam(arg.Isbn),
		duckdbListParam(arg.Extra),
	)
	return err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, email, born, rating, tags, meta, external_id, active, created_at, updated_at FROM authors ORDER BY name LIMIT $1 OFFSET $2;
`

type ListAuthorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.Email,
			&i.Born,
			duckdbDecimal(&i.Rating),
			duckdbList(&i.Tags),
			duckdbJSON(&i.Meta),
			&i.ExternalID,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSamples = `-- name: ListSamples :many
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, nuh, f4, nf4, f8, nf8, d, nd, s, ns, t, nt, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, iv, niv, u, nu, j, nj, g, ng, e, ne, li, nli, ls, nls, lu, nlu, lj, nlj, fixed, nfixed, st, nst, m, nm FROM samples;
`

func (q *Queries) ListSamples(ctx context.Context) ([]Sample, error) {
	rows, err := q.db.QueryContext(ctx, listSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sample
	for rows.Next() {
		var i Sample
		if err := rows.Scan(
			&i.ID,
			&i.B,
			&i.Nb,
			&i.I1,
			&i.Ni1,
			&i.I2,
			&i.Ni2,
			&i.I4,
			&i.Ni4,
			&i.I8,
			&i.Ni8,
			&i.U1,
			&i.Nu1,
			&i.U2,
			&i.Nu2,
			&i.U4,
			&i.Nu4,
			&i.U8,
			&i.Nu8,
			&i.H,
			&i.Nh,
			&i.Uh,
			&i.Nuh,
			&i.F4,
			&i.Nf4,
			&i.F8,
			&i.Nf8,
			duckdbDecimal(&i.D),
			duckdbDecimal(&i.Nd),
			&i.S,
			&i.Ns,
			&i.T,
			&i.Nt,
			&i.Bl,
			&i.Nbl,
			&i.Dt,
			&i.Ndt,
			&i.Tm,
			&i.Ntm,
			&i.Ts,
			&i.Nts,
			&i.Tstz,
			&i.Ntstz,
			&i.Iv,
			&i.Niv,
			&i.U,
			&i.Nu,
			duckdbJSON(&i.J),
			duckdbJSON(&i.Nj),
			&i.G,
			&i.Ng,
			&i.E,
			&i.Ne,
			duckdbList(&i.Li),
			duckdbList(&i.Nli),
			duckdbList(&i.Ls),
			duckdbList(&i.Nls),
			duckdbList(&i.Lu),
			duckdbList(&i.Nlu),
			duckdbList(&i.Lj),
			duckdbList(&i.Nlj),
			duckdbList(&i.Fixed),
			duckdbList(&i.Nfixed),
			&i.St,
			&i.Nst,
			&i.M,
			&i.Nm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyRevenue = `-- name: MonthlyRevenue :many
WITH monthly AS (
  SELECT date_trunc('month', published) AS month, genre, sum(price) AS revenue, count(*) AS n
  FROM books
  WHERE published IS NOT NULL
  GROUP BY 1, 2
)
SELECT month, genre, revenue, n,
       sum(revenue) OVER (PARTITION BY genre ORDER BY month) AS running,
       row_number() OVER (ORDER BY revenue DESC) AS rank
FROM monthly
ORDER BY month, genre;
`

type MonthlyRevenueRow struct {
	Month   *time.Time `json:"month"`
	Genre   Genre      `json:"genre"`
	Revenue *string    `json:"revenue"`
	N       int64      `json:"n"`
	Running *string    `json:"running"`
	Rank    int64      `json:"rank"`
}

func (q *Queries) MonthlyRevenue(ctx context.Context) ([]MonthlyRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, monthlyRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyRevenueRow
	for rows.Next() {
		var i MonthlyRevenueRow
		if err := rows.Scan(
			&i.Month,
			&i.Genre,
			duckdbDecimal(&i.Revenue),
			&i.N,
			duckdbDecimal(&i.Running),
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentBooks = `-- name: RecentBooks :many
SELECT id, title, created_at FROM books WHERE created_at > now() - INTERVAL 7 DAY ORDER BY created_at DESC;
`

type RecentBooksRow struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) RecentBooks(ctx context.Context) ([]RecentBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, recentBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentBooksRow
	for rows.Next() {
		var i RecentBooksRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, title, price FROM books
WHERE ($1::genre IS NULL OR genre = $1)
  AND price BETWEEN $2 AND $3
  AND title ILIKE '%' || $4 || '%';
`

type SearchBooksParams struct {
	Genre    *Genre `json:"genre"`
	MinPrice string `json:"min_price"`
	MaxPrice string `json:"max_price"`
	Q        string `json:"q"`
}

type SearchBooksRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Price string `json:"price"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooks,
		arg.Genre,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(&i.ID, &i.Title, duckdbDecimal(&i.Price)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthorBio = `-- name: UpdateAuthorBio :execrows
UPDATE authors SET bio = $1, updated_at = now() WHERE id = $2;
`

type UpdateAuthorBioParams struct {
	Bio *string `json:"bio"`
	ID  int32   `json:"id"`
}

func (q *Queries) UpdateAuthorBio(ctx context.Context, arg UpdateAuthorBioParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAuthorBio, arg.Bio, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAuthor = `-- name: UpsertAuthor :one
INSERT INTO authors (id, name, bio, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, bio = EXCLUDED.bio, updated_at = now()
RETURNING id, name, updated_at;
`

type UpsertAuthorParams struct {
	ID    int32   `json:"id"`
	Name  string  `json:"name"`
	Bio   *string `json:"bio"`
	Email *string `json:"email"`
}

type UpsertAuthorRow struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updated_at"`
}

func (q *Queries) UpsertAuthor(ctx context.Context, arg UpsertAuthorParams) (UpsertAuthorRow, error) {
	row := q.db.QueryRowContext(ctx, upsertAuthor,
		arg.ID,
		arg.Name,
		arg.Bio,
		arg.Email,
	)
	var i UpsertAuthorRow
	err := row.Scan(&i.ID, &i.Name, &i.UpdatedAt)
	return i, err
}
