//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"

	"github.com/duckdb/duckdb-go/v2"
)

const daysBack = `-- name: DaysBack :many
SELECT id FROM authors WHERE created_at >= now() - $1::BIGINT * INTERVAL '1 day';
`

func (q *Queries) DaysBack(ctx context.Context, days int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, daysBack, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expired = `-- name: Expired :many
SELECT id FROM authors WHERE created_at + $1 < now();
`

func (q *Queries) Expired(ctx context.Context, age duckdb.Interval) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, expired, age)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scaled = `-- name: Scaled :many
SELECT id, price * $1::DECIMAL(10,2) AS scaled FROM authors;
`

type ScaledRow struct {
	ID     int64
	Scaled string
}

func (q *Queries) Scaled(ctx context.Context, factor string) ([]ScaledRow, error) {
	rows, err := q.db.QueryContext(ctx, scaled, factor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScaledRow
	for rows.Next() {
		var i ScaledRow
		if err := rows.Scan(&i.ID, duckdbDecimal(&i.Scaled)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const search = `-- name: Search :many
SELECT id FROM authors WHERE name LIKE '%' || $1 || '%';
`

func (q *Queries) Search(ctx context.Context, q_ string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, search, q_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shifted = `-- name: Shifted :many
SELECT id + $1 AS shifted FROM authors;
`

func (q *Queries) Shifted(ctx context.Context, n int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, shifted, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var shifted int64
		if err := rows.Scan(&shifted); err != nil {
			return nil, err
		}
		items = append(items, shifted)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
