// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package querytest

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addSeen = `-- name: AddSeen :batchexec
INSERT INTO seen (ad_id, day, ct) SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (ad_id, day) DO UPDATE SET ct = seen.ct + EXCLUDED.ct;
`

const addSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type AddSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []AddSeenParams
	closed bool
}

type AddSeenParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

func (q *Queries) AddSeen(ctx context.Context, arg []AddSeenParams) *AddSeenBatchResults {
	return &AddSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type addSeenBatchRow struct {
	P1   int64   `json:"p1"`
	P2   *string `json:"p2"`
	P3   int32   `json:"p3"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *AddSeenBatchResults) jsonRows() []addSeenBatchRow {
	out := make([]addSeenBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = addSeenBatchRow{
			P1:   arg.AdID,
			P2:   duckdbBatchDate(arg.Day),
			P3:   arg.Ct,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *AddSeenBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), addSeen, addSeenRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *AddSeenBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *AddSeenBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const bulkPauseDaily = `-- name: BulkPauseDaily :batchexec
INSERT INTO daily (day, source, status, seen_at)
SELECT sqlc_b.p1, sqlc_b.p2, 'paused'::status, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET status = EXCLUDED.status, seen_at = EXCLUDED.seen_at;
`

const bulkPauseDailyRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type BulkPauseDailyBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkPauseDailyParams
	closed bool
}

type BulkPauseDailyParams struct {
	Days    []time.Time
	Sources []string
	Seen    []time.Time
}

func (q *Queries) BulkPauseDaily(ctx context.Context, arg []BulkPauseDailyParams) *BulkPauseDailyBatchResults {
	return &BulkPauseDailyBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkPauseDailyBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkPauseDailyBatchResults) jsonRows() []bulkPauseDailyBatchRow {
	var out []bulkPauseDailyBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.Days), len(arg.Sources), len(arg.Seen)) {
			out = append(out, bulkPauseDailyBatchRow{
				P1:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P2:   duckdbBatchAt(arg.Sources, sqlcI),
				P3:   duckdbBatchAtWith(arg.Seen, sqlcI, duckdbBatchTimestamptz),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkPauseDailyBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), bulkPauseDaily, bulkPauseDailyRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *BulkPauseDailyBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *BulkPauseDailyBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const bulkSetRevenue = `-- name: BulkSetRevenue :batchexec
INSERT INTO daily (day, source, revenue)
SELECT sqlc_b.p1, sqlc_b.p2, (sqlc_b.p3)::DOUBLE FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET revenue = EXCLUDED.revenue;
`

const bulkSetRevenueRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type BulkSetRevenueBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkSetRevenueParams
	closed bool
}

type BulkSetRevenueParams struct {
	Days     []time.Time
	Sources  []string
	Revenues []float64
}

// A float travels as text, so NaN and the infinities survive.
func (q *Queries) BulkSetRevenue(ctx context.Context, arg []BulkSetRevenueParams) *BulkSetRevenueBatchResults {
	return &BulkSetRevenueBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkSetRevenueBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkSetRevenueBatchResults) jsonRows() []bulkSetRevenueBatchRow {
	var out []bulkSetRevenueBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.Days), len(arg.Sources), len(arg.Revenues)) {
			out = append(out, bulkSetRevenueBatchRow{
				P1:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P2:   duckdbBatchAt(arg.Sources, sqlcI),
				P3:   duckdbBatchAtWith(arg.Revenues, sqlcI, duckdbBatchFloat[float64]),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkSetRevenueBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), bulkSetRevenue, bulkSetRevenueRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *BulkSetRevenueBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *BulkSetRevenueBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const bulkSetStatus = `-- name: BulkSetStatus :batchexec
INSERT INTO daily (day, source, status)
SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3::status FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET status = EXCLUDED.status;
`

const bulkSetStatusRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type BulkSetStatusBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkSetStatusParams
	closed bool
}

type BulkSetStatusParams struct {
	Days     []time.Time
	Sources  []string
	Statuses []string
}

func (q *Queries) BulkSetStatus(ctx context.Context, arg []BulkSetStatusParams) *BulkSetStatusBatchResults {
	return &BulkSetStatusBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkSetStatusBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkSetStatusBatchResults) jsonRows() []bulkSetStatusBatchRow {
	var out []bulkSetStatusBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.Days), len(arg.Sources), len(arg.Statuses)) {
			out = append(out, bulkSetStatusBatchRow{
				P1:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P2:   duckdbBatchAt(arg.Sources, sqlcI),
				P3:   duckdbBatchAt(arg.Statuses, sqlcI),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkSetStatusBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), bulkSetStatus, bulkSetStatusRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *BulkSetStatusBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *BulkSetStatusBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const bulkUpsertSeen = `-- name: BulkUpsertSeen :batchmany
INSERT INTO seen (ad_id, day, ct)
SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (ad_id, day) DO UPDATE SET ct = EXCLUDED.ct
;
`

const bulkUpsertSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

const bulkUpsertSeenRead = `SELECT sqlc_b.sqlc_elem, ad_id, ct FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN seen ON seen.ad_id = (sqlc_b.p1) AND seen.day = (sqlc_b.p2) ORDER BY sqlc_b.sqlc_ord`

type BulkUpsertSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkUpsertSeenParams
	closed bool
}

type BulkUpsertSeenParams struct {
	AdIds []int64
	Days  []time.Time
	Cts   []int32
}

type BulkUpsertSeenRow struct {
	AdID int64
	Ct   int32
}

func (q *Queries) BulkUpsertSeen(ctx context.Context, arg []BulkUpsertSeenParams) *BulkUpsertSeenBatchResults {
	return &BulkUpsertSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkUpsertSeenBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkUpsertSeenBatchResults) jsonRows() []bulkUpsertSeenBatchRow {
	var out []bulkUpsertSeenBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.AdIds), len(arg.Days), len(arg.Cts)) {
			out = append(out, bulkUpsertSeenBatchRow{
				P1:   duckdbBatchAt(arg.AdIds, sqlcI),
				P2:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P3:   duckdbBatchAt(arg.Cts, sqlcI),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkUpsertSeenBatchResults) query(items [][]BulkUpsertSeenRow) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), bulkUpsertSeen, bulkUpsertSeenRounds, bulkUpsertSeenRead, func(scan func(...any) error) error {
		var sqlcElem int
		var i BulkUpsertSeenRow
		if err := scan(&sqlcElem, &i.AdID, &i.Ct); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], i)
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *BulkUpsertSeenBatchResults) Query(f func(int, []BulkUpsertSeenRow, error)) {
	items := make([][]BulkUpsertSeenRow, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *BulkUpsertSeenBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]BulkUpsertSeenRow, len(b.rows)))
}

const countTag = `-- name: CountTag :batchexec
INSERT INTO tags (name, hits) SELECT sqlc_b.p1, 1 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (name) DO UPDATE SET hits = tags.hits + 1;
`

const countTagRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1)`

type CountTagBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []*string
	closed bool
}

// Each row whose key is NULL gets a round of its own: one INSERT ... ON
// CONFLICT keeps only one of several NULL-key rows.
func (q *Queries) CountTag(ctx context.Context, name []*string) *CountTagBatchResults {
	return &CountTagBatchResults{ctx: ctx, db: q.db, rows: name}
}

type countTagBatchRow struct {
	P1   *string `json:"p1"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *CountTagBatchResults) jsonRows() []countTagBatchRow {
	out := make([]countTagBatchRow, len(b.rows))
	for sqlcIdx, name := range b.rows {
		out[sqlcIdx] = countTagBatchRow{
			P1:   name,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *CountTagBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), countTag, countTagRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *CountTagBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *CountTagBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const hitTag = `-- name: HitTag :batchone
INSERT INTO tags (name, hits) VALUES ($1, 1)
ON CONFLICT (name) DO UPDATE SET hits = tags.hits + 1
RETURNING id;
`

type HitTagBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []*string
	closed bool
}

// A nullable key cannot be read back by key: runs row by row.
func (q *Queries) HitTag(ctx context.Context, name []*string) *HitTagBatchResults {
	return &HitTagBatchResults{ctx: ctx, db: q.db, rows: name}
}

func (b *HitTagBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for sqlcIdx, name := range b.rows {
			sqlcRows, err := db.QueryContext(b.ctx, hitTag, name)
			if err != nil {
				return err
			}
			for sqlcRows.Next() {
				var id int64
				if err := sqlcRows.Scan(&id); err != nil {
					sqlcRows.Close()
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], id)
			}
			if err := sqlcRows.Close(); err != nil {
				return err
			}
			if err := sqlcRows.Err(); err != nil {
				return err
			}
		}
		return nil
	})
}

// QueryRow runs the whole batch in one transaction and calls f once per
// row with the row it returned. When the batch fails, every row gets the
// error.
func (b *HitTagBatchResults) QueryRow(f func(int, int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		var id int64
		switch {
		case err != nil:
			f(t, id, err)
		case len(items[t]) == 0:
			f(t, id, duckdbErrNoRows)
		default:
			f(t, items[t][0], nil)
		}
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *HitTagBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]int64, len(b.rows)))
}

const insertLog = `-- name: InsertLog :batchexec
INSERT INTO log (msg) SELECT sqlc_b.p1 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b;
`

type InsertLogBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []string
	closed bool
}

func (q *Queries) InsertLog(ctx context.Context, msg []string) *InsertLogBatchResults {
	return &InsertLogBatchResults{ctx: ctx, db: q.db, rows: msg}
}

type insertLogBatchRow struct {
	P1   string `json:"p1"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *InsertLogBatchResults) jsonRows() []insertLogBatchRow {
	out := make([]insertLogBatchRow, len(b.rows))
	for sqlcIdx, msg := range b.rows {
		out[sqlcIdx] = insertLogBatchRow{
			P1:   msg,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *InsertLogBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), insertLog, "")
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *InsertLogBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *InsertLogBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const insertLogLists = `-- name: InsertLogLists :batchmany
INSERT INTO log (msg) SELECT sqlc_b.p1 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b RETURNING id;
`

type InsertLogListsBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   [][]string
	closed bool
}

func (q *Queries) InsertLogLists(ctx context.Context, msgs [][]string) *InsertLogListsBatchResults {
	return &InsertLogListsBatchResults{ctx: ctx, db: q.db, rows: msgs}
}

type insertLogListsBatchRow struct {
	P1   any `json:"p1"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *InsertLogListsBatchResults) jsonRows() []insertLogListsBatchRow {
	var out []insertLogListsBatchRow
	for sqlcIdx, msgs := range b.rows {
		for sqlcI := range duckdbBatchLen(len(msgs)) {
			out = append(out, insertLogListsBatchRow{
				P1:   duckdbBatchAt(msgs, sqlcI),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *InsertLogListsBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	all := b.jsonRows()
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		start := 0
		for sqlcIdx := range b.rows {
			end := start
			for end < len(all) && all[end].Elem == sqlcIdx {
				end++
			}
			if end == start {
				continue
			}
			err := duckdbBatchQueryEach(b.ctx, db, all[start:end], insertLogLists, func(scan func(...any) error) error {
				var id int64
				if err := scan(&id); err != nil {
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], id)
				return nil
			})
			if err != nil {
				return err
			}
			start = end
		}
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *InsertLogListsBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *InsertLogListsBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]int64, len(b.rows)))
}

const insertLogPayloadList = `-- name: InsertLogPayloadList :batchexec
INSERT INTO log (msg, payloads) VALUES ($1, $2);
`

type InsertLogPayloadListBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []InsertLogPayloadListParams
	closed bool
}

type InsertLogPayloadListParams struct {
	Msg      string
	Payloads []json.RawMessage
}

// A JSON[] would lose which elements are strings: runs row by row.
func (q *Queries) InsertLogPayloadList(ctx context.Context, arg []InsertLogPayloadListParams) *InsertLogPayloadListBatchResults {
	return &InsertLogPayloadListBatchResults{ctx: ctx, db: q.db, rows: arg}
}

func (b *InsertLogPayloadListBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for _, arg := range b.rows {
			if _, err := db.ExecContext(b.ctx, insertLogPayloadList, arg.Msg, duckdbListParam(arg.Payloads)); err != nil {
				return err
			}
		}
		return nil
	})
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *InsertLogPayloadListBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *InsertLogPayloadListBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const insertLogPayloads = `-- name: InsertLogPayloads :batchmany
INSERT INTO log (msg, payload)
SELECT sqlc_b.p1, (sqlc_b.p2)::JSON FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b
RETURNING id, payload;
`

type InsertLogPayloadsBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []InsertLogPayloadsParams
	closed bool
}

type InsertLogPayloadsParams struct {
	Msgs     []string
	Payloads []json.RawMessage
}

type InsertLogPayloadsRow struct {
	ID      int64
	Payload json.RawMessage
}

func (q *Queries) InsertLogPayloads(ctx context.Context, arg []InsertLogPayloadsParams) *InsertLogPayloadsBatchResults {
	return &InsertLogPayloadsBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type insertLogPayloadsBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *InsertLogPayloadsBatchResults) jsonRows() []insertLogPayloadsBatchRow {
	var out []insertLogPayloadsBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.Msgs), len(arg.Payloads)) {
			out = append(out, insertLogPayloadsBatchRow{
				P1:   duckdbBatchAt(arg.Msgs, sqlcI),
				P2:   duckdbBatchAtWith(arg.Payloads, sqlcI, duckdbBatchJSON[json.RawMessage]),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *InsertLogPayloadsBatchResults) query(items [][]InsertLogPayloadsRow) error {
	if len(b.rows) == 0 {
		return nil
	}
	all := b.jsonRows()
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		start := 0
		for sqlcIdx := range b.rows {
			end := start
			for end < len(all) && all[end].Elem == sqlcIdx {
				end++
			}
			if end == start {
				continue
			}
			err := duckdbBatchQueryEach(b.ctx, db, all[start:end], insertLogPayloads, func(scan func(...any) error) error {
				var i InsertLogPayloadsRow
				if err := scan(&i.ID, duckdbJSON(&i.Payload)); err != nil {
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], i)
				return nil
			})
			if err != nil {
				return err
			}
			start = end
		}
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *InsertLogPayloadsBatchResults) Query(f func(int, []InsertLogPayloadsRow, error)) {
	items := make([][]InsertLogPayloadsRow, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *InsertLogPayloadsBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]InsertLogPayloadsRow, len(b.rows)))
}

const insertLogReturning = `-- name: InsertLogReturning :batchmany
INSERT INTO log (msg) SELECT sqlc_b.p1 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b RETURNING id;
`

type InsertLogReturningBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []string
	closed bool
}

func (q *Queries) InsertLogReturning(ctx context.Context, msg []string) *InsertLogReturningBatchResults {
	return &InsertLogReturningBatchResults{ctx: ctx, db: q.db, rows: msg}
}

type insertLogReturningBatchRow struct {
	P1   string `json:"p1"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *InsertLogReturningBatchResults) jsonRows() []insertLogReturningBatchRow {
	out := make([]insertLogReturningBatchRow, len(b.rows))
	for sqlcIdx, msg := range b.rows {
		out[sqlcIdx] = insertLogReturningBatchRow{
			P1:   msg,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *InsertLogReturningBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	all := b.jsonRows()
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		start := 0
		for sqlcIdx := range b.rows {
			end := start
			for end < len(all) && all[end].Elem == sqlcIdx {
				end++
			}
			if end == start {
				continue
			}
			err := duckdbBatchQueryEach(b.ctx, db, all[start:end], insertLogReturning, func(scan func(...any) error) error {
				var id int64
				if err := scan(&id); err != nil {
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], id)
				return nil
			})
			if err != nil {
				return err
			}
			start = end
		}
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *InsertLogReturningBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *InsertLogReturningBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]int64, len(b.rows)))
}

const mergeKeywordLower = `-- name: MergeKeywordLower :batchexec
MERGE INTO keywords t
USING (VALUES ($1::VARCHAR, $2::TIMESTAMPTZ)) AS s(keyword, seen)
ON lower(t.keyword) = lower(s.keyword)
WHEN MATCHED THEN UPDATE SET last_seen = s.seen;
`

type MergeKeywordLowerBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []MergeKeywordLowerParams
	closed bool
}

type MergeKeywordLowerParams struct {
	Keyword string
	Seen    time.Time
}

// ON compares expressions, not columns: runs row by row.
func (q *Queries) MergeKeywordLower(ctx context.Context, arg []MergeKeywordLowerParams) *MergeKeywordLowerBatchResults {
	return &MergeKeywordLowerBatchResults{ctx: ctx, db: q.db, rows: arg}
}

func (b *MergeKeywordLowerBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for _, arg := range b.rows {
			if _, err := db.ExecContext(b.ctx, mergeKeywordLower, arg.Keyword, arg.Seen); err != nil {
				return err
			}
		}
		return nil
	})
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *MergeKeywordLowerBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *MergeKeywordLowerBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const mergeSeen = `-- name: MergeSeen :batchexec
MERGE INTO seen
USING (SELECT sqlc_b.p1::BIGINT, sqlc_b.p2::DATE, sqlc_b.p3::INTEGER FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1::BIGINT, sqlc_b.p2::DATE ORDER BY sqlc_b.sqlc_ord) = $2) AS s(ad_id, day, ct)
ON seen.ad_id = s.ad_id AND seen.day = s.day
WHEN MATCHED THEN UPDATE SET ct = s.ct
WHEN NOT MATCHED THEN INSERT (ad_id, day, ct) VALUES (s.ad_id, s.day, s.ct);
`

const mergeSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1::BIGINT, sqlc_b.p2::DATE)`

type MergeSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []MergeSeenParams
	closed bool
}

type MergeSeenParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

func (q *Queries) MergeSeen(ctx context.Context, arg []MergeSeenParams) *MergeSeenBatchResults {
	return &MergeSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type mergeSeenBatchRow struct {
	P1   int64   `json:"p1"`
	P2   *string `json:"p2"`
	P3   int32   `json:"p3"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *MergeSeenBatchResults) jsonRows() []mergeSeenBatchRow {
	out := make([]mergeSeenBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = mergeSeenBatchRow{
			P1:   arg.AdID,
			P2:   duckdbBatchDate(arg.Day),
			P3:   arg.Ct,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *MergeSeenBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), mergeSeen, mergeSeenRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *MergeSeenBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *MergeSeenBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const mergeSeenPrune = `-- name: MergeSeenPrune :batchexec
MERGE INTO seen
USING (VALUES ($1::BIGINT, $2::DATE, $3::INTEGER)) AS s(ad_id, day, ct)
ON seen.ad_id = s.ad_id AND seen.day = s.day
WHEN MATCHED THEN UPDATE SET ct = s.ct
WHEN NOT MATCHED BY SOURCE THEN DELETE;
`

type MergeSeenPruneBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []MergeSeenPruneParams
	closed bool
}

type MergeSeenPruneParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

// WHEN NOT MATCHED BY SOURCE would undo earlier rounds: runs row by row.
func (q *Queries) MergeSeenPrune(ctx context.Context, arg []MergeSeenPruneParams) *MergeSeenPruneBatchResults {
	return &MergeSeenPruneBatchResults{ctx: ctx, db: q.db, rows: arg}
}

func (b *MergeSeenPruneBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for _, arg := range b.rows {
			if _, err := db.ExecContext(b.ctx, mergeSeenPrune, arg.AdID, arg.Day, arg.Ct); err != nil {
				return err
			}
		}
		return nil
	})
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *MergeSeenPruneBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *MergeSeenPruneBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const setSeen = `-- name: SetSeen :batchexec
INSERT INTO seen (ad_id, day, ct) VALUES ($1, $2, $3)
ON CONFLICT (ad_id, day) DO UPDATE SET ct = $3;
`

type SetSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []SetSeenParams
	closed bool
}

type SetSeenParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

// A placeholder outside the VALUES row: runs row by row.
func (q *Queries) SetSeen(ctx context.Context, arg []SetSeenParams) *SetSeenBatchResults {
	return &SetSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

func (b *SetSeenBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for _, arg := range b.rows {
			if _, err := db.ExecContext(b.ctx, setSeen, arg.AdID, arg.Day, arg.Ct); err != nil {
				return err
			}
		}
		return nil
	})
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *SetSeenBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *SetSeenBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const upsertDaily = `-- name: UpsertDaily :batchexec
INSERT INTO daily (day, source, clicks, revenue, tags, meta, status, seen_at)
SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3, (sqlc_b.p4)::DOUBLE, sqlc_b.p5, (sqlc_b.p6)::JSON, sqlc_b.p7, sqlc_b.p8 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"BIGINT","p4":"VARCHAR","p5":"VARCHAR[]","p6":"VARCHAR","p7":"VARCHAR","p8":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET
    clicks  = EXCLUDED.clicks,
    revenue = EXCLUDED.revenue,
    tags    = EXCLUDED.tags,
    meta    = EXCLUDED.meta,
    status  = EXCLUDED.status,
    seen_at = EXCLUDED.seen_at;
`

const upsertDailyRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"BIGINT","p4":"VARCHAR","p5":"VARCHAR[]","p6":"VARCHAR","p7":"VARCHAR","p8":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type UpsertDailyBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertDailyParams
	closed bool
}

type UpsertDailyParams struct {
	Day     time.Time
	Source  string
	Clicks  *int64
	Revenue *float64
	Tags    []string
	Meta    json.RawMessage
	Status  *Status
	SeenAt  *time.Time
}

func (q *Queries) UpsertDaily(ctx context.Context, arg []UpsertDailyParams) *UpsertDailyBatchResults {
	return &UpsertDailyBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertDailyBatchRow struct {
	P1   *string  `json:"p1"`
	P2   string   `json:"p2"`
	P3   *int64   `json:"p3"`
	P4   any      `json:"p4"`
	P5   []string `json:"p5"`
	P6   *string  `json:"p6"`
	P7   *Status  `json:"p7"`
	P8   *string  `json:"p8"`
	Ord  int      `json:"sqlc_ord"`
	Elem int      `json:"sqlc_elem"`
}

func (b *UpsertDailyBatchResults) jsonRows() []upsertDailyBatchRow {
	out := make([]upsertDailyBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertDailyBatchRow{
			P1:   duckdbBatchDate(arg.Day),
			P2:   arg.Source,
			P3:   arg.Clicks,
			P4:   duckdbBatchFloat(arg.Revenue),
			P5:   arg.Tags,
			P6:   duckdbBatchJSON(arg.Meta),
			P7:   arg.Status,
			P8:   duckdbBatchTimestamptzPtr(arg.SeenAt),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertDailyBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), upsertDaily, upsertDailyRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *UpsertDailyBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *UpsertDailyBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}

const upsertKeyword = `-- name: UpsertKeyword :batchone
INSERT INTO keywords (keyword, keyword_lower, first_seen, last_seen)
SELECT sqlc_b.p1, lower(sqlc_b.p1), sqlc_b.p2, sqlc_b.p2 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY lower(sqlc_b.p1) ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (keyword_lower) DO UPDATE SET last_seen = EXCLUDED.last_seen
;
`

const upsertKeywordRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY lower(sqlc_b.p1))`

const upsertKeywordRead = `SELECT sqlc_b.sqlc_elem, keywords.* FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN keywords ON keywords.keyword_lower = (lower(sqlc_b.p1)) ORDER BY sqlc_b.sqlc_ord`

type UpsertKeywordBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertKeywordParams
	closed bool
}

type UpsertKeywordParams struct {
	Keyword string
	Seen    time.Time
}

func (q *Queries) UpsertKeyword(ctx context.Context, arg []UpsertKeywordParams) *UpsertKeywordBatchResults {
	return &UpsertKeywordBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertKeywordBatchRow struct {
	P1   string  `json:"p1"`
	P2   *string `json:"p2"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *UpsertKeywordBatchResults) jsonRows() []upsertKeywordBatchRow {
	out := make([]upsertKeywordBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertKeywordBatchRow{
			P1:   arg.Keyword,
			P2:   duckdbBatchTimestamptz(arg.Seen),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertKeywordBatchResults) query(items [][]Keyword) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), upsertKeyword, upsertKeywordRounds, upsertKeywordRead, func(scan func(...any) error) error {
		var sqlcElem int
		var i Keyword
		if err := scan(&sqlcElem,
			&i.ID,
			&i.Keyword,
			&i.KeywordLower,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], i)
		return nil
	})
}

// QueryRow runs the whole batch in one transaction and calls f once per
// row with the row it returned. When the batch fails, every row gets the
// error.
func (b *UpsertKeywordBatchResults) QueryRow(f func(int, Keyword, error)) {
	items := make([][]Keyword, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		var i Keyword
		switch {
		case err != nil:
			f(t, i, err)
		case len(items[t]) == 0:
			f(t, i, duckdbErrNoRows)
		default:
			f(t, items[t][0], nil)
		}
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *UpsertKeywordBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]Keyword, len(b.rows)))
}

const upsertKeywords = `-- name: UpsertKeywords :batchmany
INSERT INTO keywords (keyword, keyword_lower, first_seen, last_seen)
SELECT sqlc_b.p1, lower(sqlc_b.p1), sqlc_b.p2, sqlc_b.p2 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY lower(sqlc_b.p1) ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (keyword_lower) DO UPDATE SET
    first_seen = LEAST(keywords.first_seen, EXCLUDED.first_seen),
    last_seen  = GREATEST(keywords.last_seen, EXCLUDED.last_seen)
;
`

const upsertKeywordsRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY lower(sqlc_b.p1))`

const upsertKeywordsRead = `SELECT sqlc_b.sqlc_elem, id FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN keywords ON keywords.keyword_lower = (lower(sqlc_b.p1)) ORDER BY sqlc_b.sqlc_ord`

type UpsertKeywordsBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertKeywordsParams
	closed bool
}

type UpsertKeywordsParams struct {
	Keyword string
	Seen    time.Time
}

func (q *Queries) UpsertKeywords(ctx context.Context, arg []UpsertKeywordsParams) *UpsertKeywordsBatchResults {
	return &UpsertKeywordsBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertKeywordsBatchRow struct {
	P1   string  `json:"p1"`
	P2   *string `json:"p2"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *UpsertKeywordsBatchResults) jsonRows() []upsertKeywordsBatchRow {
	out := make([]upsertKeywordsBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertKeywordsBatchRow{
			P1:   arg.Keyword,
			P2:   duckdbBatchTimestamptz(arg.Seen),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertKeywordsBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), upsertKeywords, upsertKeywordsRounds, upsertKeywordsRead, func(scan func(...any) error) error {
		var sqlcElem int
		var id int64
		if err := scan(&sqlcElem, &id); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], id)
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *UpsertKeywordsBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *UpsertKeywordsBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.query(make([][]int64, len(b.rows)))
}

const upsertMetric = `-- name: UpsertMetric :batchexec
INSERT INTO metrics (id, vals, meta) SELECT sqlc_b.p1, ((sqlc_b.p2)::JSON::JSON)::DOUBLE[], (sqlc_b.p3)::JSON FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (id) DO UPDATE SET vals = EXCLUDED.vals, meta = EXCLUDED.meta;
`

const upsertMetricRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"VARCHAR","p3":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1)`

type UpsertMetricBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertMetricParams
	closed bool
}

type UpsertMetricParams struct {
	ID   int64
	Vals json.RawMessage
	Meta json.RawMessage
}

func (q *Queries) UpsertMetric(ctx context.Context, arg []UpsertMetricParams) *UpsertMetricBatchResults {
	return &UpsertMetricBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertMetricBatchRow struct {
	P1   int64   `json:"p1"`
	P2   *string `json:"p2"`
	P3   *string `json:"p3"`
	Ord  int     `json:"sqlc_ord"`
	Elem int     `json:"sqlc_elem"`
}

func (b *UpsertMetricBatchResults) jsonRows() []upsertMetricBatchRow {
	out := make([]upsertMetricBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertMetricBatchRow{
			P1:   arg.ID,
			P2:   duckdbBatchJSON(arg.Vals),
			P3:   duckdbBatchJSON(arg.Meta),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertMetricBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), upsertMetric, upsertMetricRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *UpsertMetricBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

// Close runs the batch if nothing has run it yet, and returns its error.
func (b *UpsertMetricBatchResults) Close() error {
	if b.closed {
		return nil
	}
	b.closed = true
	return b.run()
}
