// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package querytest

import (
	"context"
	"encoding/json"
	"errors"
	"time"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addSeen = `-- name: AddSeen :batchexec
INSERT INTO seen (ad_id, day, ct) SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (ad_id, day) DO UPDATE SET ct = seen.ct + EXCLUDED.ct;
`

const addSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type AddSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []AddSeenParams
	closed bool
}

type AddSeenParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

func (q *Queries) AddSeen(ctx context.Context, arg []AddSeenParams) *AddSeenBatchResults {
	return &AddSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type addSeenBatchRow struct {
	P1   int64  `json:"p1"`
	P2   string `json:"p2"`
	P3   int32  `json:"p3"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *AddSeenBatchResults) jsonRows() []addSeenBatchRow {
	out := make([]addSeenBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = addSeenBatchRow{
			P1:   arg.AdID,
			P2:   duckdbBatchDate(arg.Day),
			P3:   arg.Ct,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *AddSeenBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), addSeen, addSeenRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *AddSeenBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

func (b *AddSeenBatchResults) Close() error {
	b.closed = true
	return nil
}

const bulkPauseDaily = `-- name: BulkPauseDaily :batchexec
INSERT INTO daily (day, source, status, seen_at)
SELECT sqlc_b.p1, sqlc_b.p2, 'paused'::status, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET status = EXCLUDED.status, seen_at = EXCLUDED.seen_at;
`

const bulkPauseDailyRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type BulkPauseDailyBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkPauseDailyParams
	closed bool
}

type BulkPauseDailyParams struct {
	Days    []time.Time
	Sources []string
	Seen    []time.Time
}

func (q *Queries) BulkPauseDaily(ctx context.Context, arg []BulkPauseDailyParams) *BulkPauseDailyBatchResults {
	return &BulkPauseDailyBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkPauseDailyBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkPauseDailyBatchResults) jsonRows() []bulkPauseDailyBatchRow {
	var out []bulkPauseDailyBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.Days), len(arg.Sources), len(arg.Seen)) {
			out = append(out, bulkPauseDailyBatchRow{
				P1:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P2:   duckdbBatchAt(arg.Sources, sqlcI),
				P3:   duckdbBatchAtWith(arg.Seen, sqlcI, duckdbBatchTimestamptz),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkPauseDailyBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), bulkPauseDaily, bulkPauseDailyRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *BulkPauseDailyBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

func (b *BulkPauseDailyBatchResults) Close() error {
	b.closed = true
	return nil
}

const bulkUpsertSeen = `-- name: BulkUpsertSeen :batchmany
INSERT INTO seen (ad_id, day, ct)
SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (ad_id, day) DO UPDATE SET ct = EXCLUDED.ct
;
`

const bulkUpsertSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

const bulkUpsertSeenRead = `SELECT sqlc_b.sqlc_elem, ad_id, ct FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN seen ON seen.ad_id IS NOT DISTINCT FROM (sqlc_b.p1) AND seen.day IS NOT DISTINCT FROM (sqlc_b.p2) ORDER BY sqlc_b.sqlc_ord`

type BulkUpsertSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []BulkUpsertSeenParams
	closed bool
}

type BulkUpsertSeenParams struct {
	AdIds []int64
	Days  []time.Time
	Cts   []int32
}

type BulkUpsertSeenRow struct {
	AdID int64
	Ct   int32
}

func (q *Queries) BulkUpsertSeen(ctx context.Context, arg []BulkUpsertSeenParams) *BulkUpsertSeenBatchResults {
	return &BulkUpsertSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type bulkUpsertSeenBatchRow struct {
	P1   any `json:"p1"`
	P2   any `json:"p2"`
	P3   any `json:"p3"`
	Ord  int `json:"sqlc_ord"`
	Elem int `json:"sqlc_elem"`
}

func (b *BulkUpsertSeenBatchResults) jsonRows() []bulkUpsertSeenBatchRow {
	var out []bulkUpsertSeenBatchRow
	for sqlcIdx, arg := range b.rows {
		for sqlcI := range duckdbBatchLen(len(arg.AdIds), len(arg.Days), len(arg.Cts)) {
			out = append(out, bulkUpsertSeenBatchRow{
				P1:   duckdbBatchAt(arg.AdIds, sqlcI),
				P2:   duckdbBatchAtWith(arg.Days, sqlcI, duckdbBatchDate),
				P3:   duckdbBatchAt(arg.Cts, sqlcI),
				Ord:  len(out),
				Elem: sqlcIdx,
			})
		}
	}
	return out
}

func (b *BulkUpsertSeenBatchResults) query(items [][]BulkUpsertSeenRow) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), bulkUpsertSeen, bulkUpsertSeenRounds, bulkUpsertSeenRead, func(scan func(...any) error) error {
		var sqlcElem int
		var i BulkUpsertSeenRow
		if err := scan(&sqlcElem, &i.AdID, &i.Ct); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], i)
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *BulkUpsertSeenBatchResults) Query(f func(int, []BulkUpsertSeenRow, error)) {
	items := make([][]BulkUpsertSeenRow, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

func (b *BulkUpsertSeenBatchResults) Close() error {
	b.closed = true
	return nil
}

const insertLog = `-- name: InsertLog :batchexec
INSERT INTO log (msg) SELECT sqlc_b.p1 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b;
`

type InsertLogBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []string
	closed bool
}

func (q *Queries) InsertLog(ctx context.Context, msg []string) *InsertLogBatchResults {
	return &InsertLogBatchResults{ctx: ctx, db: q.db, rows: msg}
}

type insertLogBatchRow struct {
	P1   string `json:"p1"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *InsertLogBatchResults) jsonRows() []insertLogBatchRow {
	out := make([]insertLogBatchRow, len(b.rows))
	for sqlcIdx, msg := range b.rows {
		out[sqlcIdx] = insertLogBatchRow{
			P1:   msg,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *InsertLogBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), insertLog, "")
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *InsertLogBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

func (b *InsertLogBatchResults) Close() error {
	b.closed = true
	return nil
}

const insertLogLists = `-- name: InsertLogLists :batchmany
INSERT INTO log (msg) SELECT unnest($1::VARCHAR[]) RETURNING id;
`

type InsertLogListsBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   [][]string
	closed bool
}

func (q *Queries) InsertLogLists(ctx context.Context, msgs [][]string) *InsertLogListsBatchResults {
	return &InsertLogListsBatchResults{ctx: ctx, db: q.db, rows: msgs}
}

func (b *InsertLogListsBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for sqlcIdx, msgs := range b.rows {
			sqlcRows, err := db.QueryContext(b.ctx, insertLogLists, duckdbListParam(msgs))
			if err != nil {
				return err
			}
			for sqlcRows.Next() {
				var id int64
				if err := sqlcRows.Scan(&id); err != nil {
					sqlcRows.Close()
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], id)
			}
			if err := sqlcRows.Close(); err != nil {
				return err
			}
			if err := sqlcRows.Err(); err != nil {
				return err
			}
		}
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *InsertLogListsBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

func (b *InsertLogListsBatchResults) Close() error {
	b.closed = true
	return nil
}

const insertLogReturning = `-- name: InsertLogReturning :batchmany
INSERT INTO log (msg) VALUES ($1) RETURNING id;
`

type InsertLogReturningBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []string
	closed bool
}

func (q *Queries) InsertLogReturning(ctx context.Context, msg []string) *InsertLogReturningBatchResults {
	return &InsertLogReturningBatchResults{ctx: ctx, db: q.db, rows: msg}
}

func (b *InsertLogReturningBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbTx(b.ctx, b.db, func(db DBTX) error {
		for sqlcIdx, msg := range b.rows {
			sqlcRows, err := db.QueryContext(b.ctx, insertLogReturning, msg)
			if err != nil {
				return err
			}
			for sqlcRows.Next() {
				var id int64
				if err := sqlcRows.Scan(&id); err != nil {
					sqlcRows.Close()
					return err
				}
				items[sqlcIdx] = append(items[sqlcIdx], id)
			}
			if err := sqlcRows.Close(); err != nil {
				return err
			}
			if err := sqlcRows.Err(); err != nil {
				return err
			}
		}
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *InsertLogReturningBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

func (b *InsertLogReturningBatchResults) Close() error {
	b.closed = true
	return nil
}

const mergeSeen = `-- name: MergeSeen :batchexec
MERGE INTO seen
USING (SELECT sqlc_b.p1::BIGINT, sqlc_b.p2::DATE, sqlc_b.p3::INTEGER FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1::BIGINT, sqlc_b.p2::DATE ORDER BY sqlc_b.sqlc_ord) = $2) AS s(ad_id, day, ct)
ON seen.ad_id = s.ad_id AND seen.day = s.day
WHEN MATCHED THEN UPDATE SET ct = s.ct
WHEN NOT MATCHED THEN INSERT (ad_id, day, ct) VALUES (s.ad_id, s.day, s.ct);
`

const mergeSeenRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"BIGINT","p2":"DATE","p3":"INTEGER","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1::BIGINT, sqlc_b.p2::DATE)`

type MergeSeenBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []MergeSeenParams
	closed bool
}

type MergeSeenParams struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

func (q *Queries) MergeSeen(ctx context.Context, arg []MergeSeenParams) *MergeSeenBatchResults {
	return &MergeSeenBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type mergeSeenBatchRow struct {
	P1   int64  `json:"p1"`
	P2   string `json:"p2"`
	P3   int32  `json:"p3"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *MergeSeenBatchResults) jsonRows() []mergeSeenBatchRow {
	out := make([]mergeSeenBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = mergeSeenBatchRow{
			P1:   arg.AdID,
			P2:   duckdbBatchDate(arg.Day),
			P3:   arg.Ct,
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *MergeSeenBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), mergeSeen, mergeSeenRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *MergeSeenBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

func (b *MergeSeenBatchResults) Close() error {
	b.closed = true
	return nil
}

const upsertDaily = `-- name: UpsertDaily :batchexec
INSERT INTO daily (day, source, clicks, revenue, tags, meta, status, seen_at)
SELECT sqlc_b.p1, sqlc_b.p2, sqlc_b.p3, sqlc_b.p4, sqlc_b.p5, sqlc_b.p6, sqlc_b.p7, sqlc_b.p8 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"BIGINT","p4":"DOUBLE","p5":"VARCHAR[]","p6":"JSON","p7":"VARCHAR","p8":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY sqlc_b.p1, sqlc_b.p2 ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (day, source) DO UPDATE SET
    clicks  = EXCLUDED.clicks,
    revenue = EXCLUDED.revenue,
    tags    = EXCLUDED.tags,
    meta    = EXCLUDED.meta,
    status  = EXCLUDED.status,
    seen_at = EXCLUDED.seen_at;
`

const upsertDailyRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"DATE","p2":"VARCHAR","p3":"BIGINT","p4":"DOUBLE","p5":"VARCHAR[]","p6":"JSON","p7":"VARCHAR","p8":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY sqlc_b.p1, sqlc_b.p2)`

type UpsertDailyBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertDailyParams
	closed bool
}

type UpsertDailyParams struct {
	Day     time.Time
	Source  string
	Clicks  *int64
	Revenue *float64
	Tags    []string
	Meta    json.RawMessage
	Status  *Status
	SeenAt  *time.Time
}

func (q *Queries) UpsertDaily(ctx context.Context, arg []UpsertDailyParams) *UpsertDailyBatchResults {
	return &UpsertDailyBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertDailyBatchRow struct {
	P1   string          `json:"p1"`
	P2   string          `json:"p2"`
	P3   *int64          `json:"p3"`
	P4   *float64        `json:"p4"`
	P5   []string        `json:"p5"`
	P6   json.RawMessage `json:"p6"`
	P7   *Status         `json:"p7"`
	P8   *string         `json:"p8"`
	Ord  int             `json:"sqlc_ord"`
	Elem int             `json:"sqlc_elem"`
}

func (b *UpsertDailyBatchResults) jsonRows() []upsertDailyBatchRow {
	out := make([]upsertDailyBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertDailyBatchRow{
			P1:   duckdbBatchDate(arg.Day),
			P2:   arg.Source,
			P3:   arg.Clicks,
			P4:   arg.Revenue,
			P5:   arg.Tags,
			P6:   arg.Meta,
			P7:   arg.Status,
			P8:   duckdbBatchTimestamptzPtr(arg.SeenAt),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertDailyBatchResults) run() error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchWrite(b.ctx, b.db, b.jsonRows(), upsertDaily, upsertDailyRounds)
}

// Exec runs the whole batch in one transaction and calls f once per row,
// every row with the same error.
func (b *UpsertDailyBatchResults) Exec(f func(int, error)) {
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.run()
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		f(t, err)
	}
}

func (b *UpsertDailyBatchResults) Close() error {
	b.closed = true
	return nil
}

const upsertKeyword = `-- name: UpsertKeyword :batchone
INSERT INTO keywords (keyword, keyword_lower, first_seen, last_seen)
SELECT sqlc_b.p1, lower(sqlc_b.p1), sqlc_b.p2, sqlc_b.p2 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY lower(sqlc_b.p1) ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (keyword_lower) DO UPDATE SET last_seen = EXCLUDED.last_seen
;
`

const upsertKeywordRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY lower(sqlc_b.p1))`

const upsertKeywordRead = `SELECT sqlc_b.sqlc_elem, keywords.* FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN keywords ON keywords.keyword_lower IS NOT DISTINCT FROM (lower(sqlc_b.p1)) ORDER BY sqlc_b.sqlc_ord`

type UpsertKeywordBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertKeywordParams
	closed bool
}

type UpsertKeywordParams struct {
	Keyword string
	Seen    time.Time
}

func (q *Queries) UpsertKeyword(ctx context.Context, arg []UpsertKeywordParams) *UpsertKeywordBatchResults {
	return &UpsertKeywordBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertKeywordBatchRow struct {
	P1   string `json:"p1"`
	P2   string `json:"p2"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *UpsertKeywordBatchResults) jsonRows() []upsertKeywordBatchRow {
	out := make([]upsertKeywordBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertKeywordBatchRow{
			P1:   arg.Keyword,
			P2:   duckdbBatchTimestamptz(arg.Seen),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertKeywordBatchResults) query(items [][]Keyword) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), upsertKeyword, upsertKeywordRounds, upsertKeywordRead, func(scan func(...any) error) error {
		var sqlcElem int
		var i Keyword
		if err := scan(&sqlcElem,
			&i.ID,
			&i.Keyword,
			&i.KeywordLower,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], i)
		return nil
	})
}

// QueryRow runs the whole batch in one transaction and calls f once per
// row with the row it returned. When the batch fails, every row gets the
// error.
func (b *UpsertKeywordBatchResults) QueryRow(f func(int, Keyword, error)) {
	items := make([][]Keyword, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		var i Keyword
		switch {
		case err != nil:
			f(t, i, err)
		case len(items[t]) == 0:
			f(t, i, duckdbErrNoRows)
		default:
			f(t, items[t][0], nil)
		}
	}
}

func (b *UpsertKeywordBatchResults) Close() error {
	b.closed = true
	return nil
}

const upsertKeywords = `-- name: UpsertKeywords :batchmany
INSERT INTO keywords (keyword, keyword_lower, first_seen, last_seen)
SELECT sqlc_b.p1, lower(sqlc_b.p1), sqlc_b.p2, sqlc_b.p2 FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b QUALIFY row_number() OVER (PARTITION BY lower(sqlc_b.p1) ORDER BY sqlc_b.sqlc_ord) = $2
ON CONFLICT (keyword_lower) DO UPDATE SET
    first_seen = LEAST(keywords.first_seen, EXCLUDED.first_seen),
    last_seen  = GREATEST(keywords.last_seen, EXCLUDED.last_seen)
;
`

const upsertKeywordsRounds = `SELECT coalesce(max(n), 0)::BIGINT FROM (SELECT count(*) AS n FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b GROUP BY lower(sqlc_b.p1))`

const upsertKeywordsRead = `SELECT sqlc_b.sqlc_elem, id FROM (SELECT unnest(from_json($1::JSON, '[{"p1":"VARCHAR","p2":"TIMESTAMP WITH TIME ZONE","sqlc_ord":"BIGINT","sqlc_elem":"BIGINT"}]'), recursive := true)) AS sqlc_b JOIN keywords ON keywords.keyword_lower IS NOT DISTINCT FROM (lower(sqlc_b.p1)) ORDER BY sqlc_b.sqlc_ord`

type UpsertKeywordsBatchResults struct {
	ctx    context.Context
	db     DBTX
	rows   []UpsertKeywordsParams
	closed bool
}

type UpsertKeywordsParams struct {
	Keyword string
	Seen    time.Time
}

func (q *Queries) UpsertKeywords(ctx context.Context, arg []UpsertKeywordsParams) *UpsertKeywordsBatchResults {
	return &UpsertKeywordsBatchResults{ctx: ctx, db: q.db, rows: arg}
}

type upsertKeywordsBatchRow struct {
	P1   string `json:"p1"`
	P2   string `json:"p2"`
	Ord  int    `json:"sqlc_ord"`
	Elem int    `json:"sqlc_elem"`
}

func (b *UpsertKeywordsBatchResults) jsonRows() []upsertKeywordsBatchRow {
	out := make([]upsertKeywordsBatchRow, len(b.rows))
	for sqlcIdx, arg := range b.rows {
		out[sqlcIdx] = upsertKeywordsBatchRow{
			P1:   arg.Keyword,
			P2:   duckdbBatchTimestamptz(arg.Seen),
			Ord:  sqlcIdx,
			Elem: sqlcIdx,
		}
	}
	return out
}

func (b *UpsertKeywordsBatchResults) query(items [][]int64) error {
	if len(b.rows) == 0 {
		return nil
	}
	return duckdbBatchRead(b.ctx, b.db, b.jsonRows(), upsertKeywords, upsertKeywordsRounds, upsertKeywordsRead, func(scan func(...any) error) error {
		var sqlcElem int
		var id int64
		if err := scan(&sqlcElem, &id); err != nil {
			return err
		}
		items[sqlcElem] = append(items[sqlcElem], id)
		return nil
	})
}

// Query runs the whole batch in one transaction and calls f once per row
// with the rows that row returned. When the batch fails, every row gets
// the error.
func (b *UpsertKeywordsBatchResults) Query(f func(int, []int64, error)) {
	items := make([][]int64, len(b.rows))
	err := ErrBatchAlreadyClosed
	if !b.closed {
		err = b.query(items)
		b.closed = true
	}
	if f == nil {
		return
	}
	for t := range b.rows {
		if err != nil {
			items[t] = nil
		}
		f(t, items[t], err)
	}
}

func (b *UpsertKeywordsBatchResults) Close() error {
	b.closed = true
	return nil
}
