// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type Status string

const (
	StatusLive   Status = "live"
	StatusPaused Status = "paused"
)

func (e *Status) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value any) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Daily struct {
	Day     time.Time
	Source  string
	Clicks  *int64
	Revenue *float64
	Tags    []string
	Meta    json.RawMessage
	Status  *Status
	SeenAt  *time.Time
}

type Keyword struct {
	ID           int64
	Keyword      string
	KeywordLower string
	FirstSeen    time.Time
	LastSeen     time.Time
}

type Log struct {
	ID       int64
	Msg      string
	Payload  json.RawMessage
	Payloads []json.RawMessage
}

type Metric struct {
	ID   int64
	Vals []float64
	Meta json.RawMessage
}

type Seen struct {
	AdID int64
	Day  time.Time
	Ct   int32
}

type Tag struct {
	ID   int64
	Name *string
	Hits int32
}
