// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const predicates = `-- name: Predicates :many
SELECT id,
    NOT flag AS inactive,
    active AND flag AS both_,
    active OR flag AS either,
    NOT active AS not_active,
    bio IN ('a', 'b') AS in_list,
    score IN (5, 7) AS in_scores,
    score IN (SELECT length(bio) FROM authors) AS in_lengths,
    born BETWEEN '2000-01-01' AND '2020-01-01' AS born_in_range,
    score BETWEEN 1 AND 10 AS score_in_range,
    bio = ANY(['a']) AS any_list,
    score > ALL(SELECT length(bio) FROM authors) AS above_all,
    NOT EXISTS (SELECT 1 FROM authors a WHERE a.id > authors.id) AS is_last,
    NOT (bio IS NULL) AS has_bio
FROM authors;
`

type PredicatesRow struct {
	ID           int32
	Inactive     *bool
	Both         *bool
	Either       *bool
	NotActive    bool
	InList       *bool
	InScores     bool
	InLengths    *bool
	BornInRange  *bool
	ScoreInRange bool
	AnyList      *bool
	AboveAll     *bool
	IsLast       bool
	HasBio       bool
}

func (q *Queries) Predicates(ctx context.Context) ([]PredicatesRow, error) {
	rows, err := q.db.QueryContext(ctx, predicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PredicatesRow
	for rows.Next() {
		var i PredicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Inactive,
			&i.Both,
			&i.Either,
			&i.NotActive,
			&i.InList,
			&i.InScores,
			&i.InLengths,
			&i.BornInRange,
			&i.ScoreInRange,
			&i.AnyList,
			&i.AboveAll,
			&i.IsLast,
			&i.HasBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
