// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const cube = `-- name: Cube :many
SELECT region, name, count(*) AS c FROM authors GROUP BY CUBE (region, name);
`

type CubeRow struct {
	Region *string
	Name   *string
	C      int64
}

func (q *Queries) Cube(ctx context.Context) ([]CubeRow, error) {
	rows, err := q.db.QueryContext(ctx, cube)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CubeRow
	for rows.Next() {
		var i CubeRow
		if err := rows.Scan(&i.Region, &i.Name, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupingSets = `-- name: GroupingSets :many
SELECT region, name, count(*) AS c FROM authors GROUP BY GROUPING SETS ((region, name), (region), ());
`

type GroupingSetsRow struct {
	Region *string
	Name   *string
	C      int64
}

func (q *Queries) GroupingSets(ctx context.Context) ([]GroupingSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, groupingSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupingSetsRow
	for rows.Next() {
		var i GroupingSetsRow
		if err := rows.Scan(&i.Region, &i.Name, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const plainGroupBy = `-- name: PlainGroupBy :many
SELECT region, count(*) AS c FROM authors GROUP BY region;
`

type PlainGroupByRow struct {
	Region string
	C      int64
}

func (q *Queries) PlainGroupBy(ctx context.Context) ([]PlainGroupByRow, error) {
	rows, err := q.db.QueryContext(ctx, plainGroupBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlainGroupByRow
	for rows.Next() {
		var i PlainGroupByRow
		if err := rows.Scan(&i.Region, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rollup = `-- name: Rollup :many
SELECT region, count(*) AS c FROM authors GROUP BY ROLLUP (region);
`

type RollupRow struct {
	Region *string
	C      int64
}

func (q *Queries) Rollup(ctx context.Context) ([]RollupRow, error) {
	rows, err := q.db.QueryContext(ctx, rollup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RollupRow
	for rows.Next() {
		var i RollupRow
		if err := rows.Scan(&i.Region, &i.C); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
