// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type Code struct {
	Hash      string
	Code      *string
	IsPrivate bool
}

type TestCode struct {
	TestID   int32
	CodeHash string
}
