// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const addTestCodes = `-- name: AddTestCodes :exec
WITH input AS (SELECT DISTINCT unnest($1::TEXT[]) AS hash)
INSERT INTO test_codes (test_id, code_hash)
SELECT $2, hash FROM input
ON CONFLICT (test_id, code_hash) DO NOTHING;
`

type AddTestCodesParams struct {
	Hashes []string
	TestID int32
}

func (q *Queries) AddTestCodes(ctx context.Context, arg AddTestCodesParams) error {
	_, err := q.db.ExecContext(ctx, addTestCodes, duckdbListParam(arg.Hashes), arg.TestID)
	return err
}

const insertCode = `-- name: InsertCode :one
WITH cc AS (
    INSERT INTO codes (hash, code, is_private)
    VALUES ($1, $2, false)
    RETURNING hash
)
INSERT INTO test_codes (test_id, code_hash)
SELECT $3, hash FROM cc
RETURNING test_id, code_hash;
`

type InsertCodeParams struct {
	Hash   string
	Code   *string
	TestID int32
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) (TestCode, error) {
	row := q.db.QueryRowContext(ctx, insertCode, arg.Hash, arg.Code, arg.TestID)
	var i TestCode
	err := row.Scan(&i.TestID, &i.CodeHash)
	return i, err
}

const moveTestCodes = `-- name: MoveTestCodes :many
WITH moved AS (
    DELETE FROM test_codes WHERE test_id = $1 RETURNING code_hash
)
INSERT INTO test_codes (test_id, code_hash)
SELECT $2, code_hash FROM moved
RETURNING test_id, code_hash;
`

type MoveTestCodesParams struct {
	OldTestID int32
	NewTestID int32
}

func (q *Queries) MoveTestCodes(ctx context.Context, arg MoveTestCodesParams) ([]TestCode, error) {
	rows, err := q.db.QueryContext(ctx, moveTestCodes, arg.OldTestID, arg.NewTestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestCode
	for rows.Next() {
		var i TestCode
		if err := rows.Scan(&i.TestID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
