// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
)

type Genre string

const (
	GenreFiction Genre = "fiction"
	GenreScience Genre = "science"
)

func (e *Genre) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = Genre(s)
	case string:
		*e = Genre(s)
	default:
		return fmt.Errorf("unsupported scan type for Genre: %T", src)
	}
	return nil
}

type NullGenre struct {
	Genre Genre
	Valid bool // Valid is true if Genre is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenre) Scan(value any) error {
	if value == nil {
		ns.Genre, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Genre.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenre) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Genre), nil
}

type Part struct {
	ID      int32
	ThingID int32
	Name    *string
}

type Thing struct {
	ID int32
	Li []int32
	Ls []string
	Ld []string
	Lg []Genre
	Lu []uuid.UUID
	Ll [][]int32
}
