// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type Part struct {
	ID      int32
	ThingID int32
	Name    *string
}

type Thing struct {
	ID int32
	Li []int32
	Ls []string
	Ld []string
}
