// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const createThing = `-- name: CreateThing :exec
INSERT INTO things (id, li, ls) VALUES ($1, $2, $3);
`

type CreateThingParams struct {
	ID int32
	Li []int32
	Ls []string
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) error {
	_, err := q.db.ExecContext(ctx, createThing, arg.ID, duckdbListParam(arg.Li), duckdbListParam(arg.Ls))
	return err
}

const getThing = `-- name: GetThing :one
SELECT id, li, ls FROM things WHERE id = $1;
`

func (q *Queries) GetThing(ctx context.Context, id int32) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThing, id)
	var i Thing
	err := row.Scan(&i.ID, duckdbList(&i.Li), duckdbList(&i.Ls))
	return i, err
}

const thingPartIDs = `-- name: ThingPartIDs :many
SELECT t.id, array_agg(p.id) AS part_ids
FROM things t
LEFT JOIN parts p ON p.thing_id = t.id
GROUP BY t.id
ORDER BY t.id;
`

type ThingPartIDsRow struct {
	ID      int32
	PartIds []int32
}

// A list built in SQL may hold NULL elements: array_agg over the empty
// side of a LEFT JOIN gives [NULL]. Scanning one into []int32 is an
// error, the way a NULL scans into an int32 column.
func (q *Queries) ThingPartIDs(ctx context.Context) ([]ThingPartIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, thingPartIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ThingPartIDsRow
	for rows.Next() {
		var i ThingPartIDsRow
		if err := rows.Scan(&i.ID, duckdbList(&i.PartIds)); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
