// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package query

import (
	"context"
	"database/sql"
)

const countTagged = `-- name: CountTagged :one
SELECT count(*) FROM things WHERE tags = $1;
`

func (q *Queries) CountTagged(ctx context.Context, tags []int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagged, duckdbListParam(tags))
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createThing = `-- name: CreateThing :exec
INSERT INTO things (id, tags) VALUES ($1, $2);
`

type CreateThingParams struct {
	ID   int64
	Tags []int64
}

// An override on the element type gives a []int64 for an INTEGER[]
// column. The list is bound through a Valuer, so DuckDB casts the
// BIGINT[] the driver infers to INTEGER[] instead of the driver asserting
// int32 on each element.
func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) error {
	_, err := q.db.ExecContext(ctx, createThing, arg.ID, duckdbListParam(arg.Tags))
	return err
}

const tags = `-- name: Tags :many
SELECT unnest($1::INTEGER[]) AS tag;
`

func (q *Queries) Tags(ctx context.Context, dollar_1 []int64) ([]sql.NullInt32, error) {
	rows, err := q.db.QueryContext(ctx, tags, duckdbListParam(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullInt32
	for rows.Next() {
		var tag sql.NullInt32
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
