// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const castNotNull = `-- name: CastNotNull :many
SELECT id, CAST(score AS BIGINT) AS s FROM authors;
`

type CastNotNullRow struct {
	ID int32
	S  int64
}

func (q *Queries) CastNotNull(ctx context.Context) ([]CastNotNullRow, error) {
	rows, err := q.db.QueryContext(ctx, castNotNull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CastNotNullRow
	for rows.Next() {
		var i CastNotNullRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const castOverTry = `-- name: CastOverTry :many
SELECT id, TRY(score // 0)::BIGINT AS z FROM authors;
`

type CastOverTryRow struct {
	ID int32
	Z  *int64
}

func (q *Queries) CastOverTry(ctx context.Context) ([]CastOverTryRow, error) {
	rows, err := q.db.QueryContext(ctx, castOverTry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CastOverTryRow
	for rows.Next() {
		var i CastOverTryRow
		if err := rows.Scan(&i.ID, &i.Z); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const try = `-- name: Try :many
SELECT id, TRY(score // 0) AS z, TRY(name) AS n FROM authors;
`

type TryRow struct {
	ID int32
	Z  *int32
	N  *string
}

func (q *Queries) Try(ctx context.Context) ([]TryRow, error) {
	rows, err := q.db.QueryContext(ctx, try)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TryRow
	for rows.Next() {
		var i TryRow
		if err := rows.Scan(&i.ID, &i.Z, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCastNotNull = `-- name: TryCastNotNull :many
SELECT id, TRY_CAST(name AS INTEGER) AS n FROM authors;
`

type TryCastNotNullRow struct {
	ID int32
	N  *int32
}

func (q *Queries) TryCastNotNull(ctx context.Context) ([]TryCastNotNullRow, error) {
	rows, err := q.db.QueryContext(ctx, tryCastNotNull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TryCastNotNullRow
	for rows.Next() {
		var i TryCastNotNullRow
		if err := rows.Scan(&i.ID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCastNullable = `-- name: TryCastNullable :many
SELECT id, TRY_CAST(bio AS INTEGER) AS b FROM authors;
`

type TryCastNullableRow struct {
	ID int32
	B  *int32
}

func (q *Queries) TryCastNullable(ctx context.Context) ([]TryCastNullableRow, error) {
	rows, err := q.db.QueryContext(ctx, tryCastNullable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TryCastNullableRow
	for rows.Next() {
		var i TryCastNullableRow
		if err := rows.Scan(&i.ID, &i.B); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryCastParam = `-- name: TryCastParam :many
SELECT id FROM authors WHERE score = TRY_CAST($1 AS INTEGER);
`

func (q *Queries) TryCastParam(ctx context.Context, score int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, tryCastParam, score)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
