// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const atParams = `-- name: AtParams :many
SELECT name FROM foo WHERE name = $1;
`

func (q *Queries) AtParams(ctx context.Context, slug any) ([]any, error) {
	rows, err := q.db.QueryContext(ctx, atParams, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []any
	for rows.Next() {
		var name any
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dollarParams = `-- name: DollarParams :many
SELECT name FROM foo WHERE name = $1;
`

func (q *Queries) DollarParams(ctx context.Context, slug any) ([]any, error) {
	rows, err := q.db.QueryContext(ctx, dollarParams, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []any
	for rows.Next() {
		var name any
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const funcParams = `-- name: FuncParams :many
SELECT name FROM foo WHERE name = $1;
`

func (q *Queries) FuncParams(ctx context.Context, slug any) ([]any, error) {
	rows, err := q.db.QueryContext(ctx, funcParams, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []any
	for rows.Next() {
		var name any
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAtParams = `-- name: InsertAtParams :one
INSERT INTO foo(name, bio) values ($1, $2) returning name;
`

type InsertAtParamsParams struct {
	Name any
	Bio  any
}

func (q *Queries) InsertAtParams(ctx context.Context, arg InsertAtParamsParams) (any, error) {
	row := q.db.QueryRowContext(ctx, insertAtParams, arg.Name, arg.Bio)
	var name any
	err := row.Scan(&name)
	return name, err
}

const insertDollarParams = `-- name: InsertDollarParams :one
INSERT INTO foo(name, bio) values ($1, $2) returning name;
`

type InsertDollarParamsParams struct {
	Name any
	Bio  any
}

func (q *Queries) InsertDollarParams(ctx context.Context, arg InsertDollarParamsParams) (any, error) {
	row := q.db.QueryRowContext(ctx, insertDollarParams, arg.Name, arg.Bio)
	var name any
	err := row.Scan(&name)
	return name, err
}

const insertFuncParams = `-- name: InsertFuncParams :one
INSERT INTO foo(name, bio) values ($1, $2) returning name;
`

type InsertFuncParamsParams struct {
	Name any
	Bio  any
}

func (q *Queries) InsertFuncParams(ctx context.Context, arg InsertFuncParamsParams) (any, error) {
	row := q.db.QueryRowContext(ctx, insertFuncParams, arg.Name, arg.Bio)
	var name any
	err := row.Scan(&name)
	return name, err
}

const paging = `-- name: Paging :many
SELECT name FROM foo ORDER BY name LIMIT $1 OFFSET $2;
`

type PagingParams struct {
	PageSize   any
	PageOffset any
}

func (q *Queries) Paging(ctx context.Context, arg PagingParams) ([]any, error) {
	rows, err := q.db.QueryContext(ctx, paging, arg.PageSize, arg.PageOffset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []any
	for rows.Next() {
		var name any
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
