// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const fooLimit = `-- name: FooLimit :many
SELECT a
FROM foo
LIMIT $1;
`

func (q *Queries) FooLimit(ctx context.Context, limit int32) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, fooLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var a *string
		if err := rows.Scan(&a); err != nil {
			return nil, err
		}
		items = append(items, a)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fooLimitOffset = `-- name: FooLimitOffset :many
SELECT a
FROM foo
LIMIT $1
OFFSET $2;
`

type FooLimitOffsetParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) FooLimitOffset(ctx context.Context, arg FooLimitOffsetParams) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, fooLimitOffset, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var a *string
		if err := rows.Scan(&a); err != nil {
			return nil, err
		}
		items = append(items, a)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fooNamedLimit = `-- name: FooNamedLimit :many
SELECT a
FROM foo
LIMIT $1
OFFSET $2;
`

type FooNamedLimitParams struct {
	PageSize int32
	Skip     int32
}

func (q *Queries) FooNamedLimit(ctx context.Context, arg FooNamedLimitParams) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, fooNamedLimit, arg.PageSize, arg.Skip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var a *string
		if err := rows.Scan(&a); err != nil {
			return nil, err
		}
		items = append(items, a)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
