// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const lambdaParamInBody = `-- name: LambdaParamInBody :many
SELECT id FROM authors
WHERE list_has_any(list_transform(tags, lambda x: x || $1::VARCHAR), ['xa']) AND small = $2;
`

type LambdaParamInBodyParams struct {
	Suffix string
	Small  int32
}

func (q *Queries) LambdaParamInBody(ctx context.Context, arg LambdaParamInBodyParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, lambdaParamInBody, arg.Suffix, arg.Small)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lambdaShadowsColumn = `-- name: LambdaShadowsColumn :many
SELECT list_transform(tags, lambda name: name || '!') AS shouted, name FROM authors;
`

type LambdaShadowsColumnRow struct {
	Shouted []string
	Name    string
}

func (q *Queries) LambdaShadowsColumn(ctx context.Context) ([]LambdaShadowsColumnRow, error) {
	rows, err := q.db.QueryContext(ctx, lambdaShadowsColumn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LambdaShadowsColumnRow
	for rows.Next() {
		var i LambdaShadowsColumnRow
		if err := rows.Scan(duckdbList(&i.Shouted), &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lambdaTwoParams = `-- name: LambdaTwoParams :many
SELECT list_reduce(ints, lambda x, y: x + y + $1::INTEGER) AS total FROM authors;
`

func (q *Queries) LambdaTwoParams(ctx context.Context, acc int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, lambdaTwoParams, acc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var total int32
		if err := rows.Scan(&total); err != nil {
			return nil, err
		}
		items = append(items, total)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
