// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const positionalJoin = `-- name: PositionalJoin :many
SELECT a.id, a.name, b.id AS book_id, b.title
FROM authors a
POSITIONAL JOIN books b;
`

type PositionalJoinRow struct {
	ID     sql.NullInt32
	Name   sql.NullString
	BookID sql.NullInt32
	Title  sql.NullString
}

func (q *Queries) PositionalJoin(ctx context.Context) ([]PositionalJoinRow, error) {
	rows, err := q.db.QueryContext(ctx, positionalJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PositionalJoinRow
	for rows.Next() {
		var i PositionalJoinRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BookID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const positionalJoinSubquery = `-- name: PositionalJoinSubquery :many
SELECT a.id, b.title
FROM authors a
POSITIONAL JOIN (SELECT id, title FROM books LIMIT 1) b;
`

type PositionalJoinSubqueryRow struct {
	ID    sql.NullInt32
	Title sql.NullString
}

func (q *Queries) PositionalJoinSubquery(ctx context.Context) ([]PositionalJoinSubqueryRow, error) {
	rows, err := q.db.QueryContext(ctx, positionalJoinSubquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PositionalJoinSubqueryRow
	for rows.Next() {
		var i PositionalJoinSubqueryRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
