// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type BazUser struct {
	ID   any
	Name any
}

type Post struct {
	ID     any
	UserID any
}

type User struct {
	ID   any
	Name any
	Age  any
}
