// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type Like struct {
	PostID int64
	UserID int64
}

type Post struct {
	ID     int64
	UserID int64
	Title  string
}

type User struct {
	ID   int64
	Name string
}
