// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const fullJoinOverLeft = `-- name: FullJoinOverLeft :many
SELECT u.id, p.title, l.user_id AS liker
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
FULL JOIN likes l ON l.post_id = p.id;
`

type FullJoinOverLeftRow struct {
	ID    sql.NullInt64
	Title sql.NullString
	Liker sql.NullInt64
}

func (q *Queries) FullJoinOverLeft(ctx context.Context) ([]FullJoinOverLeftRow, error) {
	rows, err := q.db.QueryContext(ctx, fullJoinOverLeft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullJoinOverLeftRow
	for rows.Next() {
		var i FullJoinOverLeftRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Liker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const innerJoinOverLeft = `-- name: InnerJoinOverLeft :many
SELECT u.id, p.title, l.user_id AS liker
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
JOIN likes l ON l.post_id = p.id;
`

type InnerJoinOverLeftRow struct {
	ID    int64
	Title sql.NullString
	Liker int64
}

func (q *Queries) InnerJoinOverLeft(ctx context.Context) ([]InnerJoinOverLeftRow, error) {
	rows, err := q.db.QueryContext(ctx, innerJoinOverLeft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InnerJoinOverLeftRow
	for rows.Next() {
		var i InnerJoinOverLeftRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Liker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leftJoinChain = `-- name: LeftJoinChain :many
SELECT u.id, p.title, l.user_id AS liker
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
LEFT JOIN likes l ON l.post_id = p.id;
`

type LeftJoinChainRow struct {
	ID    int64
	Title sql.NullString
	Liker sql.NullInt64
}

func (q *Queries) LeftJoinChain(ctx context.Context) ([]LeftJoinChainRow, error) {
	rows, err := q.db.QueryContext(ctx, leftJoinChain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeftJoinChainRow
	for rows.Next() {
		var i LeftJoinChainRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Liker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leftJoinNested = `-- name: LeftJoinNested :many
SELECT u.id, p.title, l.user_id AS liker
FROM users u
LEFT JOIN (posts p JOIN likes l ON l.post_id = p.id) ON p.user_id = u.id;
`

type LeftJoinNestedRow struct {
	ID    int64
	Title sql.NullString
	Liker sql.NullInt64
}

func (q *Queries) LeftJoinNested(ctx context.Context) ([]LeftJoinNestedRow, error) {
	rows, err := q.db.QueryContext(ctx, leftJoinNested)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeftJoinNestedRow
	for rows.Next() {
		var i LeftJoinNestedRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Liker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rightJoinOverLeft = `-- name: RightJoinOverLeft :many
SELECT u.id, p.title, l.user_id AS liker
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
RIGHT JOIN likes l ON l.post_id = p.id;
`

type RightJoinOverLeftRow struct {
	ID    sql.NullInt64
	Title sql.NullString
	Liker int64
}

func (q *Queries) RightJoinOverLeft(ctx context.Context) ([]RightJoinOverLeftRow, error) {
	rows, err := q.db.QueryContext(ctx, rightJoinOverLeft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RightJoinOverLeftRow
	for rows.Next() {
		var i RightJoinOverLeftRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Liker); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
