// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

type Location struct {
	ID      int32
	Name    string
	Address string
	ZipCode int32
	Note    *string
	Visits  int32
}
