// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO locations (id, name, address, zip_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
  name = excluded.name,
  address = excluded.address,
  zip_code = excluded.zip_code;
`

type UpsertLocationParams struct {
	ID      int32
	Name    string
	Address string
	ZipCode int32
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocation,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ZipCode,
	)
	return err
}

const upsertLocationIfNearer = `-- name: UpsertLocationIfNearer :one
INSERT INTO locations (id, name, address, zip_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET address = excluded.address, note = $5
WHERE locations.zip_code <> excluded.zip_code
RETURNING id, note, visits;
`

type UpsertLocationIfNearerParams struct {
	ID      int32
	Name    string
	Address string
	ZipCode int32
	Note    *string
}

type UpsertLocationIfNearerRow struct {
	ID     int32
	Note   *string
	Visits int32
}

func (q *Queries) UpsertLocationIfNearer(ctx context.Context, arg UpsertLocationIfNearerParams) (UpsertLocationIfNearerRow, error) {
	row := q.db.QueryRowContext(ctx, upsertLocationIfNearer,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ZipCode,
		arg.Note,
	)
	var i UpsertLocationIfNearerRow
	err := row.Scan(&i.ID, &i.Note, &i.Visits)
	return i, err
}

const upsertLocationNote = `-- name: UpsertLocationNote :exec
INSERT INTO locations (id, name, address, zip_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET note = $5, visits = locations.visits + $6
WHERE visits < $7;
`

type UpsertLocationNoteParams struct {
	ID        int32
	Name      string
	Address   string
	ZipCode   int32
	Note      *string
	Step      int32
	MaxVisits int32
}

func (q *Queries) UpsertLocationNote(ctx context.Context, arg UpsertLocationNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocationNote,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.ZipCode,
		arg.Note,
		arg.Step,
		arg.MaxVisits,
	)
	return err
}
