// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"time"
)

type Incoming struct {
	Item string
	Day  time.Time
	Qty  int32
}

type Stock struct {
	Item    string
	Day     time.Time
	Qty     int32
	Note    *string
	Updated *time.Time
}
