// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"time"
)

const applyIncoming = `-- name: ApplyIncoming :many
MERGE INTO stock
USING incoming AS s
USING (item, day)
WHEN MATCHED AND s.qty = 0 THEN DELETE
WHEN MATCHED THEN UPDATE SET qty = stock.qty + s.qty
WHEN NOT MATCHED THEN INSERT BY NAME
WHEN NOT MATCHED BY SOURCE AND stock.day >= $1 THEN DELETE
RETURNING merge_action, item, qty;
`

type ApplyIncomingRow struct {
	MergeAction string
	Item        string
	Qty         int32
}

func (q *Queries) ApplyIncoming(ctx context.Context, since time.Time) ([]ApplyIncomingRow, error) {
	rows, err := q.db.QueryContext(ctx, applyIncoming, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplyIncomingRow
	for rows.Next() {
		var i ApplyIncomingRow
		if err := rows.Scan(&i.MergeAction, &i.Item, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDay = `-- name: ReplaceDay :many
WITH src AS (SELECT item, day, qty FROM incoming WHERE day = $1)
MERGE INTO stock
USING src
USING (item, day)
WHEN MATCHED THEN UPDATE BY NAME
WHEN NOT MATCHED THEN INSERT BY NAME
RETURNING item, day, qty, note, updated;
`

func (q *Queries) ReplaceDay(ctx context.Context, day time.Time) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, replaceDay, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stock
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.Item,
			&i.Day,
			&i.Qty,
			&i.Note,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNote = `-- name: SetNote :one
MERGE INTO stock
USING (VALUES ($1::VARCHAR, $2::DATE)) AS s(item, day)
ON stock.item = s.item AND stock.day = s.day
WHEN MATCHED THEN UPDATE SET note = $3
WHEN NOT MATCHED THEN ERROR 'no such row'
RETURNING merge_action, note;
`

type SetNoteParams struct {
	Item string
	Day  time.Time
	Note *string
}

type SetNoteRow struct {
	MergeAction string
	Note        *string
}

func (q *Queries) SetNote(ctx context.Context, arg SetNoteParams) (SetNoteRow, error) {
	row := q.db.QueryRowContext(ctx, setNote, arg.Item, arg.Day, arg.Note)
	var i SetNoteRow
	err := row.Scan(&i.MergeAction, &i.Note)
	return i, err
}

const upsertStock = `-- name: UpsertStock :exec
MERGE INTO stock
USING (SELECT $1::VARCHAR AS item, $2::DATE AS day) AS s
ON stock.item = s.item AND stock.day = s.day
WHEN MATCHED THEN UPDATE SET qty = $3, note = $4, updated = now()
WHEN NOT MATCHED THEN INSERT (item, day, qty, note) VALUES (s.item, s.day, $3, $4);
`

type UpsertStockParams struct {
	Item string
	Day  time.Time
	Qty  int32
	Note *string
}

func (q *Queries) UpsertStock(ctx context.Context, arg UpsertStockParams) error {
	_, err := q.db.ExecContext(ctx, upsertStock,
		arg.Item,
		arg.Day,
		arg.Qty,
		arg.Note,
	)
	return err
}
