// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"encoding/json"
)

const createAd = `-- name: CreateAd :exec
INSERT INTO ads (id, meta) VALUES ($1, $2);
`

type CreateAdParams struct {
	ID   int32
	Meta json.RawMessage
}

func (q *Queries) CreateAd(ctx context.Context, arg CreateAdParams) error {
	_, err := q.db.ExecContext(ctx, createAd, arg.ID, duckdbParam(arg.Meta))
	return err
}

const getAd = `-- name: GetAd :one
SELECT id, meta FROM ads WHERE id = $1;
`

func (q *Queries) GetAd(ctx context.Context, id int32) (Ad, error) {
	row := q.db.QueryRowContext(ctx, getAd, id)
	var i Ad
	err := row.Scan(&i.ID, duckdbJSON(&i.Meta))
	return i, err
}

const getAdText = `-- name: GetAdText :one
SELECT id, meta::VARCHAR AS meta_text FROM ads WHERE id = $1;
`

type GetAdTextRow struct {
	ID       int32
	MetaText string
}

// The driver decodes a JSON column, so the message a query returns is
// re-encoded and not byte for byte what was stored. The stored text comes
// back as a string through a cast.
func (q *Queries) GetAdText(ctx context.Context, id int32) (GetAdTextRow, error) {
	row := q.db.QueryRowContext(ctx, getAdText, id)
	var i GetAdTextRow
	err := row.Scan(&i.ID, &i.MetaText)
	return i, err
}
