//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"encoding/json"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

type Thing struct {
	ID    int32             `json:"id"`
	B     bool              `json:"b"`
	Nb    *bool             `json:"nb"`
	I1    int8              `json:"i1"`
	Ni1   *int8             `json:"ni1"`
	I2    int16             `json:"i2"`
	Ni2   *int16            `json:"ni2"`
	I4    int32             `json:"i4"`
	Ni4   *int32            `json:"ni4"`
	I8    int64             `json:"i8"`
	Ni8   *int64            `json:"ni8"`
	U1    uint8             `json:"u1"`
	Nu1   *uint8            `json:"nu1"`
	U2    uint16            `json:"u2"`
	Nu2   *uint16           `json:"nu2"`
	U4    uint32            `json:"u4"`
	Nu4   *uint32           `json:"nu4"`
	U8    uint64            `json:"u8"`
	Nu8   *uint64           `json:"nu8"`
	H     *big.Int          `json:"h"`
	Nh    *big.Int          `json:"nh"`
	Uh    *big.Int          `json:"uh"`
	Bn    *big.Int          `json:"bn"`
	F4    float32           `json:"f4"`
	Nf4   *float32          `json:"nf4"`
	F8    float64           `json:"f8"`
	Nf8   *float64          `json:"nf8"`
	D     string            `json:"d"`
	Nd    *string           `json:"nd"`
	N     string            `json:"n"`
	S     string            `json:"s"`
	Ns    *string           `json:"ns"`
	T     string            `json:"t"`
	Bl    []byte            `json:"bl"`
	Nbl   []byte            `json:"nbl"`
	Dt    time.Time         `json:"dt"`
	Ndt   *time.Time        `json:"ndt"`
	Tm    time.Time         `json:"tm"`
	Ntm   *time.Time        `json:"ntm"`
	Ts    time.Time         `json:"ts"`
	Nts   *time.Time        `json:"nts"`
	Tstz  time.Time         `json:"tstz"`
	Ntstz *time.Time        `json:"ntstz"`
	Tsns  time.Time         `json:"tsns"`
	Iv    duckdb.Interval   `json:"iv"`
	Niv   *duckdb.Interval  `json:"niv"`
	U     uuid.UUID         `json:"u"`
	Nu    *uuid.UUID        `json:"nu"`
	J     json.RawMessage   `json:"j"`
	Nj    json.RawMessage   `json:"nj"`
	E     string            `json:"e"`
	Ne    *string           `json:"ne"`
	Li    []int32           `json:"li"`
	Nli   []int32           `json:"nli"`
	Ls    []string          `json:"ls"`
	Lu    []uuid.UUID       `json:"lu"`
	Lj    []json.RawMessage `json:"lj"`
	Fixed []int32           `json:"fixed"`
	St    map[string]any    `json:"st"`
	Nst   *map[string]any   `json:"nst"`
	M     duckdb.Map        `json:"m"`
	Nm    *duckdb.Map       `json:"nm"`
}
