// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"encoding/json"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

const castThings = `-- name: CastThings :one
SELECT CAST($1 AS JSON) AS j, $2::INTEGER[] AS li, $3::DECIMAL(10,2) AS d, $4::UUID AS u, $5::HUGEINT AS h, $6::VARCHAR[] AS ls;
`

type CastThingsParams struct {
	Column1 json.RawMessage `json:"column_1"`
	Column2 []int32         `json:"column_2"`
	Column3 string          `json:"column_3"`
	Column4 uuid.UUID       `json:"column_4"`
	Column5 *big.Int        `json:"column_5"`
	Column6 []string        `json:"column_6"`
}

type CastThingsRow struct {
	J  json.RawMessage `json:"j"`
	Li []int32         `json:"li"`
	D  string          `json:"d"`
	U  uuid.UUID       `json:"u"`
	H  *big.Int        `json:"h"`
	Ls []string        `json:"ls"`
}

func (q *Queries) CastThings(ctx context.Context, arg CastThingsParams) (CastThingsRow, error) {
	row := q.db.QueryRowContext(ctx, castThings,
		duckdbParam(arg.Column1),
		duckdbListParam(arg.Column2),
		arg.Column3,
		arg.Column4,
		duckdbParam(arg.Column5),
		duckdbListParam(arg.Column6),
	)
	var i CastThingsRow
	err := row.Scan(
		duckdbJSON(&i.J),
		duckdbList(&i.Li),
		duckdbDecimal(&i.D),
		&i.U,
		&i.H,
		duckdbList(&i.Ls),
	)
	return i, err
}

const createThing = `-- name: CreateThing :exec
INSERT INTO things (id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62);
`

type CreateThingParams struct {
	ID    int32             `json:"id"`
	B     bool              `json:"b"`
	Nb    *bool             `json:"nb"`
	I1    int8              `json:"i1"`
	Ni1   *int8             `json:"ni1"`
	I2    int16             `json:"i2"`
	Ni2   *int16            `json:"ni2"`
	I4    int32             `json:"i4"`
	Ni4   *int32            `json:"ni4"`
	I8    int64             `json:"i8"`
	Ni8   *int64            `json:"ni8"`
	U1    uint8             `json:"u1"`
	Nu1   *uint8            `json:"nu1"`
	U2    uint16            `json:"u2"`
	Nu2   *uint16           `json:"nu2"`
	U4    uint32            `json:"u4"`
	Nu4   *uint32           `json:"nu4"`
	U8    uint64            `json:"u8"`
	Nu8   *uint64           `json:"nu8"`
	H     *big.Int          `json:"h"`
	Nh    *big.Int          `json:"nh"`
	Uh    *big.Int          `json:"uh"`
	Bn    *big.Int          `json:"bn"`
	F4    float32           `json:"f4"`
	Nf4   *float32          `json:"nf4"`
	F8    float64           `json:"f8"`
	Nf8   *float64          `json:"nf8"`
	D     string            `json:"d"`
	Nd    *string           `json:"nd"`
	N     string            `json:"n"`
	S     string            `json:"s"`
	Ns    *string           `json:"ns"`
	T     string            `json:"t"`
	Bl    []byte            `json:"bl"`
	Nbl   []byte            `json:"nbl"`
	Dt    time.Time         `json:"dt"`
	Ndt   *time.Time        `json:"ndt"`
	Tm    time.Time         `json:"tm"`
	Ntm   *time.Time        `json:"ntm"`
	Ts    time.Time         `json:"ts"`
	Nts   *time.Time        `json:"nts"`
	Tstz  time.Time         `json:"tstz"`
	Ntstz *time.Time        `json:"ntstz"`
	Tsns  time.Time         `json:"tsns"`
	Iv    duckdb.Interval   `json:"iv"`
	Niv   *duckdb.Interval  `json:"niv"`
	U     uuid.UUID         `json:"u"`
	Nu    *uuid.UUID        `json:"nu"`
	J     json.RawMessage   `json:"j"`
	Nj    json.RawMessage   `json:"nj"`
	E     string            `json:"e"`
	Ne    *string           `json:"ne"`
	Li    []int32           `json:"li"`
	Nli   []int32           `json:"nli"`
	Ls    []string          `json:"ls"`
	Lu    []uuid.UUID       `json:"lu"`
	Lj    []json.RawMessage `json:"lj"`
	Fixed []int32           `json:"fixed"`
	St    map[string]any    `json:"st"`
	Nst   *map[string]any   `json:"nst"`
	M     duckdb.Map        `json:"m"`
	Nm    *duckdb.Map       `json:"nm"`
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) error {
	_, err := q.db.ExecContext(ctx, createThing,
		arg.ID,
		arg.B,
		arg.Nb,
		arg.I1,
		arg.Ni1,
		arg.I2,
		arg.Ni2,
		arg.I4,
		arg.Ni4,
		arg.I8,
		arg.Ni8,
		arg.U1,
		arg.Nu1,
		arg.U2,
		arg.Nu2,
		arg.U4,
		arg.Nu4,
		arg.U8,
		arg.Nu8,
		duckdbParam(arg.H),
		duckdbParam(arg.Nh),
		duckdbParam(arg.Uh),
		duckdbParam(arg.Bn),
		arg.F4,
		arg.Nf4,
		arg.F8,
		arg.Nf8,
		arg.D,
		arg.Nd,
		arg.N,
		arg.S,
		arg.Ns,
		arg.T,
		duckdbParam(arg.Bl),
		duckdbParam(arg.Nbl),
		arg.Dt,
		arg.Ndt,
		arg.Tm,
		arg.Ntm,
		arg.Ts,
		arg.Nts,
		arg.Tstz,
		arg.Ntstz,
		arg.Tsns,
		arg.Iv,
		arg.Niv,
		arg.U,
		arg.Nu,
		duckdbParam(arg.J),
		duckdbParam(arg.Nj),
		arg.E,
		arg.Ne,
		duckdbListParam(arg.Li),
		duckdbListParam(arg.Nli),
		duckdbListParam(arg.Ls),
		duckdbListParam(arg.Lu),
		duckdbListParam(arg.Lj),
		duckdbListParam(arg.Fixed),
		arg.St,
		arg.Nst,
		arg.M,
		arg.Nm,
	)
	return err
}

const findThings = `-- name: FindThings :many
SELECT id, j, d, li FROM things
WHERE li = $1 AND j = $2 AND d = $3 AND u = $4 AND nj = $5;
`

type FindThingsParams struct {
	Li []int32         `json:"li"`
	J  json.RawMessage `json:"j"`
	D  string          `json:"d"`
	U  uuid.UUID       `json:"u"`
	Nj json.RawMessage `json:"nj"`
}

type FindThingsRow struct {
	ID int32           `json:"id"`
	J  json.RawMessage `json:"j"`
	D  string          `json:"d"`
	Li []int32         `json:"li"`
}

func (q *Queries) FindThings(ctx context.Context, arg FindThingsParams) ([]FindThingsRow, error) {
	rows, err := q.db.QueryContext(ctx, findThings,
		duckdbListParam(arg.Li),
		duckdbParam(arg.J),
		arg.D,
		arg.U,
		duckdbParam(arg.Nj),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindThingsRow
	for rows.Next() {
		var i FindThingsRow
		if err := rows.Scan(
			&i.ID,
			duckdbJSON(&i.J),
			duckdbDecimal(&i.D),
			duckdbList(&i.Li),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThing = `-- name: GetThing :one
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm FROM things WHERE id = $1;
`

func (q *Queries) GetThing(ctx context.Context, id int32) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThing, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.B,
		&i.Nb,
		&i.I1,
		&i.Ni1,
		&i.I2,
		&i.Ni2,
		&i.I4,
		&i.Ni4,
		&i.I8,
		&i.Ni8,
		&i.U1,
		&i.Nu1,
		&i.U2,
		&i.Nu2,
		&i.U4,
		&i.Nu4,
		&i.U8,
		&i.Nu8,
		&i.H,
		&i.Nh,
		&i.Uh,
		&i.Bn,
		&i.F4,
		&i.Nf4,
		&i.F8,
		&i.Nf8,
		duckdbDecimal(&i.D),
		duckdbDecimal(&i.Nd),
		duckdbDecimal(&i.N),
		&i.S,
		&i.Ns,
		&i.T,
		&i.Bl,
		&i.Nbl,
		&i.Dt,
		&i.Ndt,
		&i.Tm,
		&i.Ntm,
		&i.Ts,
		&i.Nts,
		&i.Tstz,
		&i.Ntstz,
		&i.Tsns,
		&i.Iv,
		&i.Niv,
		&i.U,
		&i.Nu,
		duckdbJSON(&i.J),
		duckdbJSON(&i.Nj),
		&i.E,
		&i.Ne,
		duckdbList(&i.Li),
		duckdbList(&i.Nli),
		duckdbList(&i.Ls),
		duckdbList(&i.Lu),
		duckdbList(&i.Lj),
		duckdbList(&i.Fixed),
		&i.St,
		&i.Nst,
		&i.M,
		&i.Nm,
	)
	return i, err
}

const listThings = `-- name: ListThings :many
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm FROM things;
`

func (q *Queries) ListThings(ctx context.Context) ([]Thing, error) {
	rows, err := q.db.QueryContext(ctx, listThings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thing
	for rows.Next() {
		var i Thing
		if err := rows.Scan(
			&i.ID,
			&i.B,
			&i.Nb,
			&i.I1,
			&i.Ni1,
			&i.I2,
			&i.Ni2,
			&i.I4,
			&i.Ni4,
			&i.I8,
			&i.Ni8,
			&i.U1,
			&i.Nu1,
			&i.U2,
			&i.Nu2,
			&i.U4,
			&i.Nu4,
			&i.U8,
			&i.Nu8,
			&i.H,
			&i.Nh,
			&i.Uh,
			&i.Bn,
			&i.F4,
			&i.Nf4,
			&i.F8,
			&i.Nf8,
			duckdbDecimal(&i.D),
			duckdbDecimal(&i.Nd),
			duckdbDecimal(&i.N),
			&i.S,
			&i.Ns,
			&i.T,
			&i.Bl,
			&i.Nbl,
			&i.Dt,
			&i.Ndt,
			&i.Tm,
			&i.Ntm,
			&i.Ts,
			&i.Nts,
			&i.Tstz,
			&i.Ntstz,
			&i.Tsns,
			&i.Iv,
			&i.Niv,
			&i.U,
			&i.Nu,
			duckdbJSON(&i.J),
			duckdbJSON(&i.Nj),
			&i.E,
			&i.Ne,
			duckdbList(&i.Li),
			duckdbList(&i.Nli),
			duckdbList(&i.Ls),
			duckdbList(&i.Lu),
			duckdbList(&i.Lj),
			duckdbList(&i.Fixed),
			&i.St,
			&i.Nst,
			&i.M,
			&i.Nm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oneDecimal = `-- name: OneDecimal :one
SELECT nd FROM things WHERE id = $1;
`

func (q *Queries) OneDecimal(ctx context.Context, id int32) (*string, error) {
	row := q.db.QueryRowContext(ctx, oneDecimal, id)
	var nd *string
	err := row.Scan(duckdbDecimal(&nd))
	return nd, err
}

const oneJSON = `-- name: OneJSON :one
SELECT nj FROM things WHERE id = $1;
`

func (q *Queries) OneJSON(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, oneJSON, id)
	var nj json.RawMessage
	err := row.Scan(duckdbJSON(&nj))
	return nj, err
}

const oneList = `-- name: OneList :one
SELECT li FROM things WHERE id = $1;
`

func (q *Queries) OneList(ctx context.Context, id int32) ([]int32, error) {
	row := q.db.QueryRowContext(ctx, oneList, id)
	var li []int32
	err := row.Scan(duckdbList(&li))
	return li, err
}

const sumThings = `-- name: SumThings :one
SELECT sum(i4) AS total, count(*) AS n, max(d) AS max_d, list(s) AS names FROM things;
`

type SumThingsRow struct {
	Total *big.Int `json:"total"`
	N     int64    `json:"n"`
	MaxD  *string  `json:"max_d"`
	Names []string `json:"names"`
}

func (q *Queries) SumThings(ctx context.Context) (SumThingsRow, error) {
	row := q.db.QueryRowContext(ctx, sumThings)
	var i SumThingsRow
	err := row.Scan(
		&i.Total,
		&i.N,
		duckdbDecimal(&i.MaxD),
		duckdbList(&i.Names),
	)
	return i, err
}
