// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
)

type Post struct {
	ID     int64
	UserID int64
	Title  string
	Body   sql.NullString
}

type User struct {
	ID   int64
	Name string
}
