// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const latestPostOrNone = `-- name: LatestPostOrNone :many
SELECT u.id, u.name, latest.title
FROM users u
LEFT JOIN LATERAL (
  SELECT recent.title
  FROM (
    SELECT p.id, p.title
    FROM posts p
    WHERE p.user_id = u.id AND p.title <> $1
    ORDER BY p.id DESC
    LIMIT 5
  ) recent
  LIMIT 1
) latest ON true;
`

type LatestPostOrNoneRow struct {
	ID    int64
	Name  string
	Title sql.NullString
}

func (q *Queries) LatestPostOrNone(ctx context.Context, title string) ([]LatestPostOrNoneRow, error) {
	rows, err := q.db.QueryContext(ctx, latestPostOrNone, title)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPostOrNoneRow
	for rows.Next() {
		var i LatestPostOrNoneRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestPostPerUser = `-- name: LatestPostPerUser :many
SELECT u.id, u.name, latest.title, latest.body
FROM users u, LATERAL (
  SELECT p.title, p.body
  FROM posts p
  WHERE p.user_id = u.id
  ORDER BY p.id DESC
  LIMIT 1
) latest;
`

type LatestPostPerUserRow struct {
	ID    int64
	Name  string
	Title string
	Body  sql.NullString
}

func (q *Queries) LatestPostPerUser(ctx context.Context) ([]LatestPostPerUserRow, error) {
	rows, err := q.db.QueryContext(ctx, latestPostPerUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestPostPerUserRow
	for rows.Next() {
		var i LatestPostPerUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Title,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
