// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const getCopied = `-- name: GetCopied :many
SELECT val, n FROM second_table;
`

func (q *Queries) GetCopied(ctx context.Context) ([]SecondTable, error) {
	rows, err := q.db.QueryContext(ctx, getCopied)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecondTable
	for rows.Next() {
		var i SecondTable
		if err := rows.Scan(&i.Val, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirst = `-- name: GetFirst :many
SELECT val, n FROM second_table;
`

func (q *Queries) GetFirst(ctx context.Context) ([]SecondTable, error) {
	rows, err := q.db.QueryContext(ctx, getFirst)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecondTable
	for rows.Next() {
		var i SecondTable
		if err := rows.Scan(&i.Val, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThroughView = `-- name: GetThroughView :many
SELECT val, n FROM foo_view;
`

func (q *Queries) GetThroughView(ctx context.Context) ([]FooView, error) {
	rows, err := q.db.QueryContext(ctx, getThroughView)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FooView
	for rows.Next() {
		var i FooView
		if err := rows.Scan(&i.Val, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
