// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
)

type T1 struct {
	ID int64
	Fk int64
	A  sql.NullString
}

type T2 struct {
	ID int64
	Fk int64
	B  string
}
