// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const bothSidesJoinUsing = `-- name: BothSidesJoinUsing :many
SELECT t1.fk, t2.fk FROM t1 LEFT JOIN t2 USING (fk) WHERE fk = $1;
`

type BothSidesJoinUsingRow struct {
	Fk   int64
	Fk_2 sql.NullInt64
}

func (q *Queries) BothSidesJoinUsing(ctx context.Context, fk int64) ([]BothSidesJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, bothSidesJoinUsing, fk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BothSidesJoinUsingRow
	for rows.Next() {
		var i BothSidesJoinUsingRow
		if err := rows.Scan(&i.Fk, &i.Fk_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fullJoinUsing = `-- name: FullJoinUsing :many
SELECT fk, a, b FROM t1 FULL JOIN t2 USING (fk);
`

type FullJoinUsingRow struct {
	Fk int64
	A  sql.NullString
	B  sql.NullString
}

func (q *Queries) FullJoinUsing(ctx context.Context) ([]FullJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, fullJoinUsing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullJoinUsingRow
	for rows.Next() {
		var i FullJoinUsingRow
		if err := rows.Scan(&i.Fk, &i.A, &i.B); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leftJoinUsing = `-- name: LeftJoinUsing :many
SELECT fk, a, b FROM t1 LEFT JOIN t2 USING (fk);
`

type LeftJoinUsingRow struct {
	Fk int64
	A  sql.NullString
	B  sql.NullString
}

func (q *Queries) LeftJoinUsing(ctx context.Context) ([]LeftJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, leftJoinUsing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeftJoinUsingRow
	for rows.Next() {
		var i LeftJoinUsingRow
		if err := rows.Scan(&i.Fk, &i.A, &i.B); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const naturalJoin = `-- name: NaturalJoin :many
SELECT id, fk, a, b FROM t1 NATURAL LEFT JOIN t2;
`

type NaturalJoinRow struct {
	ID int64
	Fk int64
	A  sql.NullString
	B  sql.NullString
}

func (q *Queries) NaturalJoin(ctx context.Context) ([]NaturalJoinRow, error) {
	rows, err := q.db.QueryContext(ctx, naturalJoin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NaturalJoinRow
	for rows.Next() {
		var i NaturalJoinRow
		if err := rows.Scan(
			&i.ID,
			&i.Fk,
			&i.A,
			&i.B,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rightJoinUsing = `-- name: RightJoinUsing :many
SELECT fk, a, b FROM t1 RIGHT JOIN t2 USING (fk);
`

type RightJoinUsingRow struct {
	Fk int64
	A  sql.NullString
	B  string
}

func (q *Queries) RightJoinUsing(ctx context.Context) ([]RightJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, rightJoinUsing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RightJoinUsingRow
	for rows.Next() {
		var i RightJoinUsingRow
		if err := rows.Scan(&i.Fk, &i.A, &i.B); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectJoinUsing = `-- name: SelectJoinUsing :many
SELECT t1.fk, count(t2.id) AS n FROM t1 JOIN t2 USING (fk) GROUP BY fk;
`

type SelectJoinUsingRow struct {
	Fk int64
	N  int64
}

func (q *Queries) SelectJoinUsing(ctx context.Context) ([]SelectJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, selectJoinUsing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectJoinUsingRow
	for rows.Next() {
		var i SelectJoinUsingRow
		if err := rows.Scan(&i.Fk, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const starJoinUsing = `-- name: StarJoinUsing :many
SELECT t1.id, fk, a, t2.id, b FROM t1 LEFT JOIN t2 USING (fk);
`

type StarJoinUsingRow struct {
	ID   int64
	Fk   int64
	A    sql.NullString
	ID_2 sql.NullInt64
	B    sql.NullString
}

func (q *Queries) StarJoinUsing(ctx context.Context) ([]StarJoinUsingRow, error) {
	rows, err := q.db.QueryContext(ctx, starJoinUsing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StarJoinUsingRow
	for rows.Next() {
		var i StarJoinUsingRow
		if err := rows.Scan(
			&i.ID,
			&i.Fk,
			&i.A,
			&i.ID_2,
			&i.B,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
