// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const authorsWithFake = `-- name: AuthorsWithFake :many
WITH q AS (
  SELECT authors.id, authors.name, fake.id AS fake_id, fake.bio AS fake_bio
  FROM authors
  LEFT JOIN fake ON authors.name = fake.name
)
SELECT id, name, fake_id, fake_bio
FROM q AS c1
WHERE c1.name = $1 AND c1.fake_id = $2;
`

type AuthorsWithFakeParams struct {
	Name string
	ID   sql.NullInt64
}

type AuthorsWithFakeRow struct {
	ID      int64
	Name    string
	FakeID  sql.NullInt64
	FakeBio sql.NullString
}

func (q *Queries) AuthorsWithFake(ctx context.Context, arg AuthorsWithFakeParams) ([]AuthorsWithFakeRow, error) {
	rows, err := q.db.QueryContext(ctx, authorsWithFake, arg.Name, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsWithFakeRow
	for rows.Next() {
		var i AuthorsWithFakeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FakeID,
			&i.FakeBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorsWithFakeTwice = `-- name: AuthorsWithFakeTwice :many
WITH q AS (
  SELECT authors.id, authors.name, fake.id AS fake_id
  FROM authors
  LEFT JOIN fake ON authors.name = fake.name
), r AS (
  SELECT q.id, q.fake_id, fake.bio
  FROM q
  LEFT JOIN fake ON fake.id = q.fake_id
)
SELECT id, fake_id, bio FROM r;
`

type AuthorsWithFakeTwiceRow struct {
	ID     int64
	FakeID sql.NullInt64
	Bio    sql.NullString
}

func (q *Queries) AuthorsWithFakeTwice(ctx context.Context) ([]AuthorsWithFakeTwiceRow, error) {
	rows, err := q.db.QueryContext(ctx, authorsWithFakeTwice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorsWithFakeTwiceRow
	for rows.Next() {
		var i AuthorsWithFakeTwiceRow
		if err := rows.Scan(&i.ID, &i.FakeID, &i.Bio); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
