// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
	"encoding/json"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

type Thing struct {
	ID    int32
	B     bool
	Nb    sql.NullBool
	I1    int8
	Ni1   sql.NullInt16
	I2    int16
	Ni2   sql.NullInt16
	I4    int32
	Ni4   sql.NullInt32
	I8    int64
	Ni8   sql.NullInt64
	U1    uint8
	Nu1   sql.Null[uint8]
	U2    uint16
	Nu2   sql.Null[uint16]
	U4    uint32
	Nu4   sql.Null[uint32]
	U8    uint64
	Nu8   sql.Null[uint64]
	H     *big.Int
	Nh    *big.Int
	Uh    *big.Int
	Bn    *big.Int
	F4    float32
	Nf4   sql.Null[float32]
	F8    float64
	Nf8   sql.NullFloat64
	D     string
	Nd    sql.NullString
	N     string
	S     string
	Ns    sql.NullString
	T     string
	Bl    []byte
	Nbl   []byte
	Dt    time.Time
	Ndt   sql.NullTime
	Tm    time.Time
	Ntm   sql.NullTime
	Ts    time.Time
	Nts   sql.NullTime
	Tstz  time.Time
	Ntstz sql.NullTime
	Tsns  time.Time
	Iv    duckdb.Interval
	Niv   sql.Null[duckdb.Interval]
	U     uuid.UUID
	Nu    uuid.NullUUID
	J     json.RawMessage
	Nj    json.RawMessage
	E     string
	Ne    sql.NullString
	Li    []int32
	Nli   []int32
	Ls    []string
	Lu    []uuid.UUID
	Lj    []json.RawMessage
	Fixed []int32
	St    map[string]any
	Nst   sql.Null[map[string]any]
	M     duckdb.Map
	Nm    sql.Null[duckdb.Map]
}
