// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
	"encoding/json"
	"math/big"
	"time"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

const castThings = `-- name: CastThings :one
SELECT CAST($1 AS JSON) AS j, $2::INTEGER[] AS li, $3::DECIMAL(10,2) AS d, $4::UUID AS u, $5::HUGEINT AS h, $6::VARCHAR[] AS ls;
`

type CastThingsParams struct {
	Column1 json.RawMessage
	Column2 []int32
	Column3 string
	Column4 uuid.UUID
	Column5 *big.Int
	Column6 []string
}

type CastThingsRow struct {
	J  json.RawMessage
	Li []int32
	D  string
	U  uuid.UUID
	H  *big.Int
	Ls []string
}

func (q *Queries) CastThings(ctx context.Context, arg CastThingsParams) (CastThingsRow, error) {
	row := q.db.QueryRowContext(ctx, castThings,
		duckdbParam(arg.Column1),
		duckdbListParam(arg.Column2),
		arg.Column3,
		arg.Column4,
		duckdbParam(arg.Column5),
		duckdbListParam(arg.Column6),
	)
	var i CastThingsRow
	err := row.Scan(
		duckdbJSON(&i.J),
		duckdbList(&i.Li),
		duckdbDecimal(&i.D),
		&i.U,
		&i.H,
		duckdbList(&i.Ls),
	)
	return i, err
}

const createThing = `-- name: CreateThing :exec
INSERT INTO things (id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62);
`

type CreateThingParams struct {
	ID    int32
	B     bool
	Nb    sql.NullBool
	I1    int8
	Ni1   sql.NullInt16
	I2    int16
	Ni2   sql.NullInt16
	I4    int32
	Ni4   sql.NullInt32
	I8    int64
	Ni8   sql.NullInt64
	U1    uint8
	Nu1   sql.Null[uint8]
	U2    uint16
	Nu2   sql.Null[uint16]
	U4    uint32
	Nu4   sql.Null[uint32]
	U8    uint64
	Nu8   sql.Null[uint64]
	H     *big.Int
	Nh    *big.Int
	Uh    *big.Int
	Bn    *big.Int
	F4    float32
	Nf4   sql.Null[float32]
	F8    float64
	Nf8   sql.NullFloat64
	D     string
	Nd    sql.NullString
	N     string
	S     string
	Ns    sql.NullString
	T     string
	Bl    []byte
	Nbl   []byte
	Dt    time.Time
	Ndt   sql.NullTime
	Tm    time.Time
	Ntm   sql.NullTime
	Ts    time.Time
	Nts   sql.NullTime
	Tstz  time.Time
	Ntstz sql.NullTime
	Tsns  time.Time
	Iv    duckdb.Interval
	Niv   sql.Null[duckdb.Interval]
	U     uuid.UUID
	Nu    uuid.NullUUID
	J     json.RawMessage
	Nj    json.RawMessage
	E     string
	Ne    sql.NullString
	Li    []int32
	Nli   []int32
	Ls    []string
	Lu    []uuid.UUID
	Lj    []json.RawMessage
	Fixed []int32
	St    map[string]any
	Nst   sql.Null[map[string]any]
	M     duckdb.Map
	Nm    sql.Null[duckdb.Map]
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) error {
	_, err := q.db.ExecContext(ctx, createThing,
		arg.ID,
		arg.B,
		arg.Nb,
		arg.I1,
		arg.Ni1,
		arg.I2,
		arg.Ni2,
		arg.I4,
		arg.Ni4,
		arg.I8,
		arg.Ni8,
		arg.U1,
		arg.Nu1,
		arg.U2,
		arg.Nu2,
		arg.U4,
		arg.Nu4,
		arg.U8,
		arg.Nu8,
		duckdbParam(arg.H),
		duckdbParam(arg.Nh),
		duckdbParam(arg.Uh),
		duckdbParam(arg.Bn),
		arg.F4,
		arg.Nf4,
		arg.F8,
		arg.Nf8,
		arg.D,
		arg.Nd,
		arg.N,
		arg.S,
		arg.Ns,
		arg.T,
		duckdbParam(arg.Bl),
		duckdbParam(arg.Nbl),
		arg.Dt,
		arg.Ndt,
		arg.Tm,
		arg.Ntm,
		arg.Ts,
		arg.Nts,
		arg.Tstz,
		arg.Ntstz,
		arg.Tsns,
		arg.Iv,
		arg.Niv,
		arg.U,
		arg.Nu,
		duckdbParam(arg.J),
		duckdbParam(arg.Nj),
		arg.E,
		arg.Ne,
		duckdbListParam(arg.Li),
		duckdbListParam(arg.Nli),
		duckdbListParam(arg.Ls),
		duckdbListParam(arg.Lu),
		duckdbListParam(arg.Lj),
		duckdbListParam(arg.Fixed),
		arg.St,
		arg.Nst,
		arg.M,
		arg.Nm,
	)
	return err
}

const findThings = `-- name: FindThings :many
SELECT id, j, d, li FROM things
WHERE li = $1 AND j = $2 AND d = $3 AND u = $4 AND nj = $5;
`

type FindThingsParams struct {
	Li []int32
	J  json.RawMessage
	D  string
	U  uuid.UUID
	Nj json.RawMessage
}

type FindThingsRow struct {
	ID int32
	J  json.RawMessage
	D  string
	Li []int32
}

func (q *Queries) FindThings(ctx context.Context, arg FindThingsParams) ([]FindThingsRow, error) {
	rows, err := q.db.QueryContext(ctx, findThings,
		duckdbListParam(arg.Li),
		duckdbParam(arg.J),
		arg.D,
		arg.U,
		duckdbParam(arg.Nj),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindThingsRow
	for rows.Next() {
		var i FindThingsRow
		if err := rows.Scan(
			&i.ID,
			duckdbJSON(&i.J),
			duckdbDecimal(&i.D),
			duckdbList(&i.Li),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThing = `-- name: GetThing :one
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm FROM things WHERE id = $1;
`

func (q *Queries) GetThing(ctx context.Context, id int32) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThing, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.B,
		&i.Nb,
		&i.I1,
		&i.Ni1,
		&i.I2,
		&i.Ni2,
		&i.I4,
		&i.Ni4,
		&i.I8,
		&i.Ni8,
		&i.U1,
		&i.Nu1,
		&i.U2,
		&i.Nu2,
		&i.U4,
		&i.Nu4,
		&i.U8,
		&i.Nu8,
		&i.H,
		&i.Nh,
		&i.Uh,
		&i.Bn,
		&i.F4,
		&i.Nf4,
		&i.F8,
		&i.Nf8,
		duckdbDecimal(&i.D),
		duckdbDecimal(&i.Nd),
		duckdbDecimal(&i.N),
		&i.S,
		&i.Ns,
		&i.T,
		&i.Bl,
		&i.Nbl,
		&i.Dt,
		&i.Ndt,
		&i.Tm,
		&i.Ntm,
		&i.Ts,
		&i.Nts,
		&i.Tstz,
		&i.Ntstz,
		&i.Tsns,
		&i.Iv,
		&i.Niv,
		&i.U,
		&i.Nu,
		duckdbJSON(&i.J),
		duckdbJSON(&i.Nj),
		&i.E,
		&i.Ne,
		duckdbList(&i.Li),
		duckdbList(&i.Nli),
		duckdbList(&i.Ls),
		duckdbList(&i.Lu),
		duckdbList(&i.Lj),
		duckdbList(&i.Fixed),
		&i.St,
		&i.Nst,
		&i.M,
		&i.Nm,
	)
	return i, err
}

const listThings = `-- name: ListThings :many
SELECT id, b, nb, i1, ni1, i2, ni2, i4, ni4, i8, ni8, u1, nu1, u2, nu2, u4, nu4, u8, nu8, h, nh, uh, bn, f4, nf4, f8, nf8, d, nd, n, s, ns, t, bl, nbl, dt, ndt, tm, ntm, ts, nts, tstz, ntstz, tsns, iv, niv, u, nu, j, nj, e, ne, li, nli, ls, lu, lj, fixed, st, nst, m, nm FROM things;
`

func (q *Queries) ListThings(ctx context.Context) ([]Thing, error) {
	rows, err := q.db.QueryContext(ctx, listThings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thing
	for rows.Next() {
		var i Thing
		if err := rows.Scan(
			&i.ID,
			&i.B,
			&i.Nb,
			&i.I1,
			&i.Ni1,
			&i.I2,
			&i.Ni2,
			&i.I4,
			&i.Ni4,
			&i.I8,
			&i.Ni8,
			&i.U1,
			&i.Nu1,
			&i.U2,
			&i.Nu2,
			&i.U4,
			&i.Nu4,
			&i.U8,
			&i.Nu8,
			&i.H,
			&i.Nh,
			&i.Uh,
			&i.Bn,
			&i.F4,
			&i.Nf4,
			&i.F8,
			&i.Nf8,
			duckdbDecimal(&i.D),
			duckdbDecimal(&i.Nd),
			duckdbDecimal(&i.N),
			&i.S,
			&i.Ns,
			&i.T,
			&i.Bl,
			&i.Nbl,
			&i.Dt,
			&i.Ndt,
			&i.Tm,
			&i.Ntm,
			&i.Ts,
			&i.Nts,
			&i.Tstz,
			&i.Ntstz,
			&i.Tsns,
			&i.Iv,
			&i.Niv,
			&i.U,
			&i.Nu,
			duckdbJSON(&i.J),
			duckdbJSON(&i.Nj),
			&i.E,
			&i.Ne,
			duckdbList(&i.Li),
			duckdbList(&i.Nli),
			duckdbList(&i.Ls),
			duckdbList(&i.Lu),
			duckdbList(&i.Lj),
			duckdbList(&i.Fixed),
			&i.St,
			&i.Nst,
			&i.M,
			&i.Nm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oneDecimal = `-- name: OneDecimal :one
SELECT nd FROM things WHERE id = $1;
`

func (q *Queries) OneDecimal(ctx context.Context, id int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, oneDecimal, id)
	var nd sql.NullString
	err := row.Scan(duckdbDecimal(&nd))
	return nd, err
}

const oneJSON = `-- name: OneJSON :one
SELECT nj FROM things WHERE id = $1;
`

func (q *Queries) OneJSON(ctx context.Context, id int32) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, oneJSON, id)
	var nj json.RawMessage
	err := row.Scan(duckdbJSON(&nj))
	return nj, err
}

const oneList = `-- name: OneList :one
SELECT li FROM things WHERE id = $1;
`

func (q *Queries) OneList(ctx context.Context, id int32) ([]int32, error) {
	row := q.db.QueryRowContext(ctx, oneList, id)
	var li []int32
	err := row.Scan(duckdbList(&li))
	return li, err
}

const sumThings = `-- name: SumThings :one
SELECT sum(i4) AS total, count(*) AS n, max(d) AS max_d, list(s) AS names FROM things;
`

type SumThingsRow struct {
	Total *big.Int
	N     int64
	MaxD  sql.NullString
	Names []string
}

func (q *Queries) SumThings(ctx context.Context) (SumThingsRow, error) {
	row := q.db.QueryRowContext(ctx, sumThings)
	var i SumThingsRow
	err := row.Scan(
		&i.Total,
		&i.N,
		duckdbDecimal(&i.MaxD),
		duckdbList(&i.Names),
	)
	return i, err
}
