// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const mixedDecimal = `-- name: MixedDecimal :one
SELECT
    price * 2 AS doubled,
    price + stock AS plus_big,
    2 * price AS twice,
    price - 1 AS less_one,
    price % 2 AS remainder,
    price / 2 AS half,
    price // 2 AS half_floor,
    price + weight AS plus_double
FROM items WHERE id = $1;
`

type MixedDecimalRow struct {
	Doubled    string
	PlusBig    string
	Twice      string
	LessOne    string
	Remainder  string
	Half       float64
	HalfFloor  float64
	PlusDouble float64
}

func (q *Queries) MixedDecimal(ctx context.Context, id int32) (MixedDecimalRow, error) {
	row := q.db.QueryRowContext(ctx, mixedDecimal, id)
	var i MixedDecimalRow
	err := row.Scan(
		duckdbDecimal(&i.Doubled),
		duckdbDecimal(&i.PlusBig),
		duckdbDecimal(&i.Twice),
		duckdbDecimal(&i.LessOne),
		duckdbDecimal(&i.Remainder),
		&i.Half,
		&i.HalfFloor,
		&i.PlusDouble,
	)
	return i, err
}
