// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"encoding/json"
	"time"
)

type Event struct {
	ID    int64
	Meta  json.RawMessage
	Seen  time.Time
	Label string
	Score float64
}
