// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"time"
)

const datePart = `-- name: DatePart :many
SELECT id, date_part($1, seen) AS part FROM events;
`

type DatePartRow struct {
	ID   int64
	Part *float64
}

func (q *Queries) DatePart(ctx context.Context, part string) ([]DatePartRow, error) {
	rows, err := q.db.QueryContext(ctx, datePart, part)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DatePartRow
	for rows.Next() {
		var i DatePartRow
		if err := rows.Scan(&i.ID, &i.Part); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jsonArrow = `-- name: JsonArrow :many
SELECT id FROM events WHERE meta->>$1::VARCHAR = $2;
`

type JsonArrowParams struct {
	Key   string
	Value *string
}

func (q *Queries) JsonArrow(ctx context.Context, arg JsonArrowParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, jsonArrow, arg.Key, arg.Value)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quantile = `-- name: Quantile :one
SELECT quantile(score, $1) AS q FROM events;
`

func (q *Queries) Quantile(ctx context.Context, q_ float64) (*float64, error) {
	row := q.db.QueryRowContext(ctx, quantile, q_)
	var q__2 *float64
	err := row.Scan(&q__2)
	return q__2, err
}

const regexpGroup = `-- name: RegexpGroup :many
SELECT id, regexp_extract(label, '([a-z]+)', $1::INTEGER) AS word FROM events;
`

type RegexpGroupRow struct {
	ID   int64
	Word string
}

func (q *Queries) RegexpGroup(ctx context.Context, grp int32) ([]RegexpGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, regexpGroup, grp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegexpGroupRow
	for rows.Next() {
		var i RegexpGroupRow
		if err := rows.Scan(&i.ID, &i.Word); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const strptime = `-- name: Strptime :many
SELECT id, strptime(label, $1) AS parsed FROM events;
`

type StrptimeRow struct {
	ID     int64
	Parsed *time.Time
}

func (q *Queries) Strptime(ctx context.Context, format string) ([]StrptimeRow, error) {
	rows, err := q.db.QueryContext(ctx, strptime, format)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StrptimeRow
	for rows.Next() {
		var i StrptimeRow
		if err := rows.Scan(&i.ID, &i.Parsed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
