// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const exceptKeepsLeft = `-- name: ExceptKeepsLeft :many
SELECT bio FROM editors EXCEPT SELECT bio FROM authors;
`

func (q *Queries) ExceptKeepsLeft(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, exceptKeepsLeft)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bio string
		if err := rows.Scan(&bio); err != nil {
			return nil, err
		}
		items = append(items, bio)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unionInCTE = `-- name: UnionInCTE :many
WITH people AS (SELECT id, name FROM authors UNION ALL SELECT NULL, NULL)
SELECT id, name FROM people;
`

type UnionInCTERow struct {
	ID   *int32
	Name *string
}

func (q *Queries) UnionInCTE(ctx context.Context) ([]UnionInCTERow, error) {
	rows, err := q.db.QueryContext(ctx, unionInCTE)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnionInCTERow
	for rows.Next() {
		var i UnionInCTERow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unionInSubquery = `-- name: UnionInSubquery :many
SELECT p.id FROM (SELECT id FROM editors UNION ALL SELECT NULL) p;
`

func (q *Queries) UnionInSubquery(ctx context.Context) ([]*int32, error) {
	rows, err := q.db.QueryContext(ctx, unionInSubquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*int32
	for rows.Next() {
		var id *int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unionNotNull = `-- name: UnionNotNull :many
SELECT id, name FROM authors UNION ALL SELECT id, name FROM editors;
`

type UnionNotNullRow struct {
	ID   int32
	Name string
}

func (q *Queries) UnionNotNull(ctx context.Context) ([]UnionNotNullRow, error) {
	rows, err := q.db.QueryContext(ctx, unionNotNull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnionNotNullRow
	for rows.Next() {
		var i UnionNotNullRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unionNullLiteral = `-- name: UnionNullLiteral :many
SELECT id, name FROM authors UNION ALL SELECT NULL, NULL;
`

type UnionNullLiteralRow struct {
	ID   *int32
	Name *string
}

func (q *Queries) UnionNullLiteral(ctx context.Context) ([]UnionNullLiteralRow, error) {
	rows, err := q.db.QueryContext(ctx, unionNullLiteral)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnionNullLiteralRow
	for rows.Next() {
		var i UnionNullLiteralRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unionNullableRight = `-- name: UnionNullableRight :many
SELECT name AS label FROM editors UNION SELECT bio FROM authors;
`

func (q *Queries) UnionNullableRight(ctx context.Context) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, unionNullableRight)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var label *string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
