// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql/driver"
	"fmt"
)

type HrLevel string

const (
	HrLevelJunior HrLevel = "junior"
	HrLevelSenior HrLevel = "senior"
)

func (e *HrLevel) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = HrLevel(s)
	case string:
		*e = HrLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for HrLevel: %T", src)
	}
	return nil
}

type NullHrLevel struct {
	HrLevel HrLevel
	Valid   bool // Valid is true if HrLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHrLevel) Scan(value any) error {
	if value == nil {
		ns.HrLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HrLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHrLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HrLevel), nil
}

type Mood string

const (
	MoodSad   Mood = "sad"
	MoodOk    Mood = "ok"
	MoodHappy Mood = "happy"
)

func (e *Mood) Scan(src any) error {
	switch s := src.(type) {
	case []byte:
		*e = Mood(s)
	case string:
		*e = Mood(s)
	default:
		return fmt.Errorf("unsupported scan type for Mood: %T", src)
	}
	return nil
}

type NullMood struct {
	Mood  Mood
	Valid bool // Valid is true if Mood is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMood) Scan(value any) error {
	if value == nil {
		ns.Mood, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Mood.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMood) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Mood), nil
}

type Person struct {
	ID          any
	Name        any
	CurrentMood any
	LastMood    any
	Lvl         any
}
