// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const createHappyPerson = `-- name: CreateHappyPerson :exec
INSERT INTO people (id, name, current_mood) VALUES ($1, $2, 'happy');
`

type CreateHappyPersonParams struct {
	ID   int32
	Name string
}

func (q *Queries) CreateHappyPerson(ctx context.Context, arg CreateHappyPersonParams) error {
	_, err := q.db.ExecContext(ctx, createHappyPerson, arg.ID, arg.Name)
	return err
}

const createPerson = `-- name: CreatePerson :exec
INSERT INTO people (id, name, current_mood, last_mood, lvl)
VALUES ($1, $2, $3, $4, $5);
`

type CreatePersonParams struct {
	ID          int32
	Name        string
	CurrentMood Mood
	LastMood    NullMood
	Lvl         NullHrLevel
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson,
		arg.ID,
		arg.Name,
		arg.CurrentMood,
		arg.LastMood,
		arg.Lvl,
	)
	return err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, current_mood, last_mood, lvl FROM people WHERE id = $1;
`

func (q *Queries) GetPerson(ctx context.Context, id int32) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentMood,
		&i.LastMood,
		&i.Lvl,
	)
	return i, err
}

const listByLevel = `-- name: ListByLevel :many
SELECT id, name FROM people WHERE lvl = $1;
`

type ListByLevelRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListByLevel(ctx context.Context, lvl NullHrLevel) ([]ListByLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, listByLevel, lvl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByLevelRow
	for rows.Next() {
		var i ListByLevelRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByMood = `-- name: ListByMood :many
SELECT id, name, current_mood FROM people WHERE current_mood = $1;
`

type ListByMoodRow struct {
	ID          int32
	Name        string
	CurrentMood Mood
}

func (q *Queries) ListByMood(ctx context.Context, currentMood Mood) ([]ListByMoodRow, error) {
	rows, err := q.db.QueryContext(ctx, listByMood, currentMood)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListByMoodRow
	for rows.Next() {
		var i ListByMoodRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CurrentMood); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHappy = `-- name: ListHappy :many
SELECT id, name FROM people WHERE current_mood = 'happy';
`

type ListHappyRow struct {
	ID   int32
	Name string
}

func (q *Queries) ListHappy(ctx context.Context) ([]ListHappyRow, error) {
	rows, err := q.db.QueryContext(ctx, listHappy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHappyRow
	for rows.Next() {
		var i ListHappyRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLastMood = `-- name: SetLastMood :exec
UPDATE people SET last_mood = $2 WHERE id = $1;
`

type SetLastMoodParams struct {
	ID       int32
	LastMood NullMood
}

func (q *Queries) SetLastMood(ctx context.Context, arg SetLastMoodParams) error {
	_, err := q.db.ExecContext(ctx, setLastMood, arg.ID, arg.LastMood)
	return err
}
