// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
)

const likeEscape = `-- name: LikeEscape :many
SELECT id FROM authors WHERE name LIKE $1 ESCAPE '\';
`

func (q *Queries) LikeEscape(ctx context.Context, pat string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, likeEscape, pat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeEscapeColumn = `-- name: LikeEscapeColumn :many
SELECT id, bio LIKE $1 ESCAPE $2 AS matches FROM authors;
`

type LikeEscapeColumnParams struct {
	Pat string
	Esc string
}

type LikeEscapeColumnRow struct {
	ID      int64
	Matches *bool
}

func (q *Queries) LikeEscapeColumn(ctx context.Context, arg LikeEscapeColumnParams) ([]LikeEscapeColumnRow, error) {
	rows, err := q.db.QueryContext(ctx, likeEscapeColumn, arg.Pat, arg.Esc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LikeEscapeColumnRow
	for rows.Next() {
		var i LikeEscapeColumnRow
		if err := rows.Scan(&i.ID, &i.Matches); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeEscapeParam = `-- name: LikeEscapeParam :many
SELECT id FROM authors WHERE name LIKE $1 ESCAPE $2;
`

type LikeEscapeParamParams struct {
	Pat string
	Esc string
}

func (q *Queries) LikeEscapeParam(ctx context.Context, arg LikeEscapeParamParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, likeEscapeParam, arg.Pat, arg.Esc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notILikeEscapeParam = `-- name: NotILikeEscapeParam :many
SELECT id FROM authors WHERE name NOT ILIKE $1 ESCAPE $2;
`

type NotILikeEscapeParamParams struct {
	Pat string
	Esc string
}

func (q *Queries) NotILikeEscapeParam(ctx context.Context, arg NotILikeEscapeParamParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, notILikeEscapeParam, arg.Pat, arg.Esc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
