// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
)

const selectUserByDollarName = `-- name: SelectUserByDollarName :many
SELECT first_name
FROM users
WHERE first_name = $1
   OR last_name = $1;
`

func (q *Queries) SelectUserByDollarName(ctx context.Context, name sql.NullString) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectUserByDollarName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var first_name sql.NullString
		if err := rows.Scan(&first_name); err != nil {
			return nil, err
		}
		items = append(items, first_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserByID = `-- name: SelectUserByID :many
SELECT first_name from
users where ($1 = id OR $1 = 0);
`

func (q *Queries) SelectUserByID(ctx context.Context, id int32) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectUserByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var first_name sql.NullString
		if err := rows.Scan(&first_name); err != nil {
			return nil, err
		}
		items = append(items, first_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserByName = `-- name: SelectUserByName :many
SELECT first_name
FROM users
WHERE first_name = $1
   OR last_name = $1;
`

func (q *Queries) SelectUserByName(ctx context.Context, name sql.NullString) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectUserByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var first_name sql.NullString
		if err := rows.Scan(&first_name); err != nil {
			return nil, err
		}
		items = append(items, first_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserMixed = `-- name: SelectUserMixed :many
SELECT first_name from
users where ($1 = id OR $3 = first_name OR $2 = 0);
`

type SelectUserMixedParams struct {
	ID      int32
	Column2 int32
	Name    sql.NullString
}

func (q *Queries) SelectUserMixed(ctx context.Context, arg SelectUserMixedParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectUserMixed, arg.ID, arg.Column2, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var first_name sql.NullString
		if err := rows.Scan(&first_name); err != nil {
			return nil, err
		}
		items = append(items, first_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserQuestion = `-- name: SelectUserQuestion :many
SELECT first_name from
users where ($1 = id OR  $1 = 0);
`

func (q *Queries) SelectUserQuestion(ctx context.Context, id int32) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, selectUserQuestion, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var first_name sql.NullString
		if err := rows.Scan(&first_name); err != nil {
			return nil, err
		}
		items = append(items, first_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
