//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"database/sql"
	"math/big"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

type Thing struct {
	ID int32
	Iv sql.Null[duckdb.Interval]
	M  sql.Null[duckdb.Map]
	H  *big.Int
	U  uuid.NullUUID
	F4 sql.Null[float32]
	St sql.Null[map[string]any]
}
