//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"database/sql"
	"math/big"

	"github.com/duckdb/duckdb-go/v2"
	"github.com/google/uuid"
)

const getThing = `-- name: GetThing :one
SELECT id, iv, m, h, u, f4, st FROM things WHERE id = $1;
`

func (q *Queries) GetThing(ctx context.Context, id int32) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThing, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		&i.Iv,
		&i.M,
		&i.H,
		&i.U,
		&i.F4,
		&i.St,
	)
	return i, err
}

const oneInterval = `-- name: OneInterval :one
SELECT iv FROM things WHERE id = $1;
`

func (q *Queries) OneInterval(ctx context.Context, id int32) (sql.Null[duckdb.Interval], error) {
	row := q.db.QueryRowContext(ctx, oneInterval, id)
	var iv sql.Null[duckdb.Interval]
	err := row.Scan(&iv)
	return iv, err
}

const setInterval = `-- name: SetInterval :exec
UPDATE things SET iv = $1, m = $2, h = $3, u = $4, f4 = $5 WHERE id = $6;
`

type SetIntervalParams struct {
	Iv sql.Null[duckdb.Interval]
	M  sql.Null[duckdb.Map]
	H  *big.Int
	U  uuid.NullUUID
	F4 sql.Null[float32]
	ID int32
}

func (q *Queries) SetInterval(ctx context.Context, arg SetIntervalParams) error {
	_, err := q.db.ExecContext(ctx, setInterval,
		duckdbNullParam(arg.Iv),
		duckdbNullParam(arg.M),
		duckdbParam(arg.H),
		arg.U,
		arg.F4,
		arg.ID,
	)
	return err
}
