// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package override

import (
	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
	"github.com/sqlc-dev/pqtype"
)

type Thing struct {
	ID       int32
	Price    pgtype.Numeric
	Discount *float64
	Meta     pqtype.NullRawMessage
	TextMeta *string
	Ref      uuid.UUID
	Parent   *string
	Prices   []pgtype.Numeric
}
