// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package override

import (
	"context"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgtype"
	"github.com/sqlc-dev/pqtype"
)

const createThing = `-- name: CreateThing :exec
INSERT INTO things (id, price, discount, meta, text_meta, ref, parent)
VALUES ($1, $2, $3, $4, $5, $6, $7);
`

type CreateThingParams struct {
	ID       int32
	Price    pgtype.Numeric
	Discount *float64
	Meta     pqtype.NullRawMessage
	TextMeta *string
	Ref      uuid.UUID
	Parent   *string
}

func (q *Queries) CreateThing(ctx context.Context, arg CreateThingParams) error {
	_, err := q.db.ExecContext(ctx, createThing,
		arg.ID,
		arg.Price,
		arg.Discount,
		arg.Meta,
		arg.TextMeta,
		arg.Ref,
		arg.Parent,
	)
	return err
}

const getThing = `-- name: GetThing :one
SELECT id, price, discount, meta, text_meta, ref, parent, prices FROM things WHERE id = $1;
`

func (q *Queries) GetThing(ctx context.Context, id int32) (Thing, error) {
	row := q.db.QueryRowContext(ctx, getThing, id)
	var i Thing
	err := row.Scan(
		&i.ID,
		duckdbDecimal(&i.Price),
		duckdbDecimal(&i.Discount),
		duckdbJSON(&i.Meta),
		duckdbJSON(&i.TextMeta),
		&i.Ref,
		duckdbUUID(&i.Parent),
		duckdbList(&i.Prices),
	)
	return i, err
}
