//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"time"
)

type Author struct {
	ID        int64
	Small     int32
	CreatedAt time.Time
}
