//go:build cgo

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"math/big"

	"github.com/duckdb/duckdb-go/v2"
)

const windowDefaultFrame = `-- name: WindowDefaultFrame :many
SELECT id, sum(small) OVER (ORDER BY id) AS s
FROM authors;
`

type WindowDefaultFrameRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowDefaultFrame(ctx context.Context) ([]WindowDefaultFrameRow, error) {
	rows, err := q.db.QueryContext(ctx, windowDefaultFrame)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowDefaultFrameRow
	for rows.Next() {
		var i WindowDefaultFrameRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowFrame = `-- name: WindowFrame :many
SELECT id, sum(small) OVER (ORDER BY id ROWS BETWEEN $1 PRECEDING AND CURRENT ROW) AS s
FROM authors;
`

type WindowFrameRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowFrame(ctx context.Context, n int32) ([]WindowFrameRow, error) {
	rows, err := q.db.QueryContext(ctx, windowFrame, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowFrameRow
	for rows.Next() {
		var i WindowFrameRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowFrameBothBounds = `-- name: WindowFrameBothBounds :many
SELECT id, sum(small) OVER (ORDER BY id ROWS BETWEEN 1 PRECEDING AND $1 FOLLOWING) AS s
FROM authors
WHERE small = $2;
`

type WindowFrameBothBoundsParams struct {
	M int32
	N int32
}

type WindowFrameBothBoundsRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowFrameBothBounds(ctx context.Context, arg WindowFrameBothBoundsParams) ([]WindowFrameBothBoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, windowFrameBothBounds, arg.M, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowFrameBothBoundsRow
	for rows.Next() {
		var i WindowFrameBothBoundsRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowGroups = `-- name: WindowGroups :many
SELECT id, sum(small) OVER (ORDER BY small GROUPS BETWEEN $1 PRECEDING AND CURRENT ROW) AS s
FROM authors;
`

type WindowGroupsRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowGroups(ctx context.Context, n int32) ([]WindowGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, windowGroups, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowGroupsRow
	for rows.Next() {
		var i WindowGroupsRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowNamed = `-- name: WindowNamed :many
SELECT id, sum(small) OVER w AS s
FROM authors
WINDOW w AS (ORDER BY id ROWS BETWEEN $1 PRECEDING AND CURRENT ROW);
`

type WindowNamedRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowNamed(ctx context.Context, n int32) ([]WindowNamedRow, error) {
	rows, err := q.db.QueryContext(ctx, windowNamed, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowNamedRow
	for rows.Next() {
		var i WindowNamedRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowRange = `-- name: WindowRange :many
SELECT id, sum(small) OVER (ORDER BY created_at RANGE BETWEEN $1::INTERVAL PRECEDING AND CURRENT ROW) AS s
FROM authors;
`

type WindowRangeRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowRange(ctx context.Context, iv duckdb.Interval) ([]WindowRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, windowRange, iv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowRangeRow
	for rows.Next() {
		var i WindowRangeRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const windowRangeNumber = `-- name: WindowRangeNumber :many
SELECT id, sum(small) OVER (ORDER BY small RANGE BETWEEN $1::INTEGER PRECEDING AND $2::INTEGER FOLLOWING) AS s
FROM authors;
`

type WindowRangeNumberParams struct {
	Lo int32
	Hi int32
}

type WindowRangeNumberRow struct {
	ID int64
	S  *big.Int
}

func (q *Queries) WindowRangeNumber(ctx context.Context, arg WindowRangeNumberParams) ([]WindowRangeNumberRow, error) {
	rows, err := q.db.QueryContext(ctx, windowRangeNumber, arg.Lo, arg.Hi)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WindowRangeNumberRow
	for rows.Next() {
		var i WindowRangeNumberRow
		if err := rows.Scan(&i.ID, &i.S); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
