// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"bytes"
	"database/sql"
	"encoding/json"
	"fmt"
	"math/big"
	"reflect"
)

// The helpers below sit between the generated code and
// github.com/duckdb/duckdb-go/v2. The driver hands database/sql a LIST as
// []any, a JSON column decoded and a DECIMAL as its own Decimal value, so
// those scan through a wrapper; and it binds a JSON message, a big
// integer and a nil slice only in a form of its own, so those are
// converted on the way in.
//
// A JSON column is not byte-stable through this driver: it decodes the
// text with encoding/json, so a number passes through float64 (an
// integer above 2^53 loses precision), keys come back sorted, and the
// JSON literal null reads as SQL NULL. Select j::VARCHAR to get the stored
// text as a string.

// duckdbList scans a LIST into a Go slice, each element the way a column of
// its type scans. NULL scans as a nil slice.
func duckdbList[T any](dst *[]T) sql.Scanner {
	return duckdbListScanner[T]{dst}
}

type duckdbListScanner[T any] struct {
	dst *[]T
}

func (s duckdbListScanner[T]) Scan(src any) error {
	if src == nil {
		*s.dst = nil
		return nil
	}
	items, ok := src.([]any)
	if !ok {
		return fmt.Errorf("cannot scan %T into []%T", src, *new(T))
	}
	out := make([]T, len(items))
	for i, item := range items {
		if err := duckdbScanValue(&out[i], item); err != nil {
			return err
		}
	}
	*s.dst = out
	return nil
}

// duckdbListParam binds a list parameter. A nil slice is NULL, a JSON
// element is handed over as the string the driver takes, and so is an
// element of a named string type such as a generated enum, which the
// driver does not know; every other slice binds as it is.
func duckdbListParam[T any](v []T) any {
	if v == nil {
		return nil
	}
	if msgs, ok := any(v).([]json.RawMessage); ok {
		out := make([]string, len(msgs))
		for i, m := range msgs {
			out[i] = string(m)
		}
		return out
	}
	if elem := reflect.TypeOf(v).Elem(); elem.Kind() == reflect.String && elem != reflect.TypeOf("") {
		out := make([]string, len(v))
		for i := range v {
			out[i] = reflect.ValueOf(v[i]).String()
		}
		return out
	}
	return v
}

// duckdbJSON scans a JSON column, which the driver decodes, back into its
// text. NULL scans as a nil message.
func duckdbJSON(dst *json.RawMessage) sql.Scanner {
	return duckdbJSONScanner{dst}
}

type duckdbJSONScanner struct {
	dst *json.RawMessage
}

func (s duckdbJSONScanner) Scan(src any) error {
	if src == nil {
		*s.dst = nil
		return nil
	}
	b, err := duckdbJSONText(src)
	if err != nil {
		return err
	}
	*s.dst = b
	return nil
}

// duckdbJSONText encodes the value the driver decoded a JSON column into
// back to JSON text, with & < > left as they are.
func duckdbJSONText(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return bytes.TrimSpace(buf.Bytes()), nil
}

// duckdbParam binds a JSON message, a BLOB or a big integer. A nil one is
// NULL, which the driver would otherwise bind as an empty value or read as
// a number; and a JSON message is handed over as the bytes the driver
// takes.
func duckdbParam(v any) any {
	switch v := v.(type) {
	case json.RawMessage:
		if v == nil {
			return nil
		}
		return []byte(v)
	case []byte:
		if v == nil {
			return nil
		}
	case *big.Int:
		if v == nil {
			return nil
		}
	}
	return v
}

// duckdbDecimal scans a DECIMAL into the text of the number.
func duckdbDecimal[T any](dst *T) sql.Scanner {
	return duckdbDecimalScanner[T]{dst}
}

type duckdbDecimalScanner[T any] struct {
	dst *T
}

func (s duckdbDecimalScanner[T]) Scan(src any) error {
	if str, ok := src.(fmt.Stringer); ok {
		src = str.String()
	}
	return duckdbScanValue(s.dst, src)
}

// duckdbScanValue scans one value into dst: through its Scan method when
// it has one, and through database/sql's own conversion otherwise.
func duckdbScanValue[T any](dst *T, src any) error {
	switch d := any(dst).(type) {
	case *json.RawMessage:
		return duckdbJSON(d).Scan(src)
	case sql.Scanner:
		return d.Scan(src)
	}
	var n sql.Null[T]
	if err := n.Scan(src); err != nil {
		return err
	}
	*dst = n.V
	return nil
}
